// Copyright (c) 2025-present Octelium Labs, LLC. All rights reserved.
//
// This software is licensed under the Octelium Enterprise Source-Available License.
// Commercial and production use is strictly prohibited without a valid
// Commercial Agreement from Octelium Labs, LLC.
//
// See the LICENSE file in the repository root for full license text.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: enterprisev1.proto

package enterprisev1

import (
	context "context"
	corev1 "github.com/octelium/octelium/apis/main/corev1"
	metav1 "github.com/octelium/octelium/apis/main/metav1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MainService_GetClusterConfig_FullMethodName                    = "/octelium.api.main.enterprise.v1.MainService/GetClusterConfig"
	MainService_UpdateClusterConfig_FullMethodName                 = "/octelium.api.main.enterprise.v1.MainService/UpdateClusterConfig"
	MainService_CreateCollectorExporter_FullMethodName             = "/octelium.api.main.enterprise.v1.MainService/CreateCollectorExporter"
	MainService_GetCollectorExporter_FullMethodName                = "/octelium.api.main.enterprise.v1.MainService/GetCollectorExporter"
	MainService_ListCollectorExporter_FullMethodName               = "/octelium.api.main.enterprise.v1.MainService/ListCollectorExporter"
	MainService_UpdateCollectorExporter_FullMethodName             = "/octelium.api.main.enterprise.v1.MainService/UpdateCollectorExporter"
	MainService_DeleteCollectorExporter_FullMethodName             = "/octelium.api.main.enterprise.v1.MainService/DeleteCollectorExporter"
	MainService_GetDNSProvider_FullMethodName                      = "/octelium.api.main.enterprise.v1.MainService/GetDNSProvider"
	MainService_ListDNSProvider_FullMethodName                     = "/octelium.api.main.enterprise.v1.MainService/ListDNSProvider"
	MainService_UpdateDNSProvider_FullMethodName                   = "/octelium.api.main.enterprise.v1.MainService/UpdateDNSProvider"
	MainService_GetCertificate_FullMethodName                      = "/octelium.api.main.enterprise.v1.MainService/GetCertificate"
	MainService_UpdateCertificate_FullMethodName                   = "/octelium.api.main.enterprise.v1.MainService/UpdateCertificate"
	MainService_ListCertificate_FullMethodName                     = "/octelium.api.main.enterprise.v1.MainService/ListCertificate"
	MainService_IssueCertificate_FullMethodName                    = "/octelium.api.main.enterprise.v1.MainService/IssueCertificate"
	MainService_GetCertificateIssuer_FullMethodName                = "/octelium.api.main.enterprise.v1.MainService/GetCertificateIssuer"
	MainService_ListCertificateIssuer_FullMethodName               = "/octelium.api.main.enterprise.v1.MainService/ListCertificateIssuer"
	MainService_UpdateCertificateIssuer_FullMethodName             = "/octelium.api.main.enterprise.v1.MainService/UpdateCertificateIssuer"
	MainService_CreateDirectoryProvider_FullMethodName             = "/octelium.api.main.enterprise.v1.MainService/CreateDirectoryProvider"
	MainService_GetDirectoryProvider_FullMethodName                = "/octelium.api.main.enterprise.v1.MainService/GetDirectoryProvider"
	MainService_ListDirectoryProvider_FullMethodName               = "/octelium.api.main.enterprise.v1.MainService/ListDirectoryProvider"
	MainService_UpdateDirectoryProvider_FullMethodName             = "/octelium.api.main.enterprise.v1.MainService/UpdateDirectoryProvider"
	MainService_DeleteDirectoryProvider_FullMethodName             = "/octelium.api.main.enterprise.v1.MainService/DeleteDirectoryProvider"
	MainService_GenerateDirectoryProviderCredential_FullMethodName = "/octelium.api.main.enterprise.v1.MainService/GenerateDirectoryProviderCredential"
	MainService_ListDirectoryProviderUser_FullMethodName           = "/octelium.api.main.enterprise.v1.MainService/ListDirectoryProviderUser"
	MainService_ListDirectoryProviderGroup_FullMethodName          = "/octelium.api.main.enterprise.v1.MainService/ListDirectoryProviderGroup"
	MainService_SynchronizeDirectoryProvider_FullMethodName        = "/octelium.api.main.enterprise.v1.MainService/SynchronizeDirectoryProvider"
	MainService_CreateSecret_FullMethodName                        = "/octelium.api.main.enterprise.v1.MainService/CreateSecret"
	MainService_ListSecret_FullMethodName                          = "/octelium.api.main.enterprise.v1.MainService/ListSecret"
	MainService_DeleteSecret_FullMethodName                        = "/octelium.api.main.enterprise.v1.MainService/DeleteSecret"
	MainService_GetSecret_FullMethodName                           = "/octelium.api.main.enterprise.v1.MainService/GetSecret"
	MainService_UpdateSecret_FullMethodName                        = "/octelium.api.main.enterprise.v1.MainService/UpdateSecret"
	MainService_GetSecretStore_FullMethodName                      = "/octelium.api.main.enterprise.v1.MainService/GetSecretStore"
	MainService_ListSecretStore_FullMethodName                     = "/octelium.api.main.enterprise.v1.MainService/ListSecretStore"
	MainService_UpdateSecretStore_FullMethodName                   = "/octelium.api.main.enterprise.v1.MainService/UpdateSecretStore"
	MainService_CreateDeviceManager_FullMethodName                 = "/octelium.api.main.enterprise.v1.MainService/CreateDeviceManager"
	MainService_GetDeviceManager_FullMethodName                    = "/octelium.api.main.enterprise.v1.MainService/GetDeviceManager"
	MainService_ListDeviceManager_FullMethodName                   = "/octelium.api.main.enterprise.v1.MainService/ListDeviceManager"
	MainService_UpdateDeviceManager_FullMethodName                 = "/octelium.api.main.enterprise.v1.MainService/UpdateDeviceManager"
	MainService_DeleteDeviceManager_FullMethodName                 = "/octelium.api.main.enterprise.v1.MainService/DeleteDeviceManager"
	MainService_GetCoreCondition_FullMethodName                    = "/octelium.api.main.enterprise.v1.MainService/GetCoreCondition"
)

// MainServiceClient is the client API for MainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MainServiceClient interface {
	// GetClusterConfig gets the Cluster Configuration.
	GetClusterConfig(ctx context.Context, in *GetClusterConfigRequest, opts ...grpc.CallOption) (*ClusterConfig, error)
	// UpdateConfig updates the Cluster Configuration.
	UpdateClusterConfig(ctx context.Context, in *ClusterConfig, opts ...grpc.CallOption) (*ClusterConfig, error)
	CreateCollectorExporter(ctx context.Context, in *CollectorExporter, opts ...grpc.CallOption) (*CollectorExporter, error)
	GetCollectorExporter(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*CollectorExporter, error)
	ListCollectorExporter(ctx context.Context, in *ListCollectorExporterOptions, opts ...grpc.CallOption) (*CollectorExporterList, error)
	UpdateCollectorExporter(ctx context.Context, in *CollectorExporter, opts ...grpc.CallOption) (*CollectorExporter, error)
	DeleteCollectorExporter(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error)
	// rpc CreateDNSProvider(DNSProvider) returns (DNSProvider) {}
	GetDNSProvider(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*DNSProvider, error)
	ListDNSProvider(ctx context.Context, in *ListDNSProviderOptions, opts ...grpc.CallOption) (*DNSProviderList, error)
	UpdateDNSProvider(ctx context.Context, in *DNSProvider, opts ...grpc.CallOption) (*DNSProvider, error)
	// rpc CreateCertificate(Certificate) returns (Certificate) {}
	GetCertificate(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Certificate, error)
	UpdateCertificate(ctx context.Context, in *Certificate, opts ...grpc.CallOption) (*Certificate, error)
	ListCertificate(ctx context.Context, in *ListCertificateOptions, opts ...grpc.CallOption) (*CertificateList, error)
	IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error)
	// rpc CreateCertificateIssuer(CertificateIssuer) returns (CertificateIssuer)
	// {}
	GetCertificateIssuer(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*CertificateIssuer, error)
	ListCertificateIssuer(ctx context.Context, in *ListCertificateIssuerOptions, opts ...grpc.CallOption) (*CertificateIssuerList, error)
	UpdateCertificateIssuer(ctx context.Context, in *CertificateIssuer, opts ...grpc.CallOption) (*CertificateIssuer, error)
	CreateDirectoryProvider(ctx context.Context, in *DirectoryProvider, opts ...grpc.CallOption) (*DirectoryProvider, error)
	GetDirectoryProvider(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*DirectoryProvider, error)
	ListDirectoryProvider(ctx context.Context, in *ListDirectoryProviderOptions, opts ...grpc.CallOption) (*DirectoryProviderList, error)
	UpdateDirectoryProvider(ctx context.Context, in *DirectoryProvider, opts ...grpc.CallOption) (*DirectoryProvider, error)
	DeleteDirectoryProvider(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error)
	GenerateDirectoryProviderCredential(ctx context.Context, in *GenerateDirectoryProviderCredentialRequest, opts ...grpc.CallOption) (*GenerateDirectoryProviderCredentialResponse, error)
	ListDirectoryProviderUser(ctx context.Context, in *ListDirectoryProviderUserOptions, opts ...grpc.CallOption) (*DirectoryProviderUserList, error)
	ListDirectoryProviderGroup(ctx context.Context, in *ListDirectoryProviderGroupOptions, opts ...grpc.CallOption) (*DirectoryProviderGroupList, error)
	SynchronizeDirectoryProvider(ctx context.Context, in *SynchronizeDirectoryProviderRequest, opts ...grpc.CallOption) (*SynchronizeDirectoryProviderResponse, error)
	// CreateSecret creates a Secret
	CreateSecret(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Secret, error)
	// ListSecret lists Secrets
	ListSecret(ctx context.Context, in *ListSecretOptions, opts ...grpc.CallOption) (*SecretList, error)
	// DeleteSecret deletes a Secret
	DeleteSecret(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error)
	// GetSecret retrieves a specific Secret
	GetSecret(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Secret, error)
	// UpdateSecret creates a Secret
	UpdateSecret(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Secret, error)
	// rpc CreateSecretStore(SecretStore) returns (SecretStore) {}
	GetSecretStore(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*SecretStore, error)
	ListSecretStore(ctx context.Context, in *ListSecretStoreOptions, opts ...grpc.CallOption) (*SecretStoreList, error)
	UpdateSecretStore(ctx context.Context, in *SecretStore, opts ...grpc.CallOption) (*SecretStore, error)
	CreateDeviceManager(ctx context.Context, in *DeviceManager, opts ...grpc.CallOption) (*DeviceManager, error)
	GetDeviceManager(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*DeviceManager, error)
	ListDeviceManager(ctx context.Context, in *ListDeviceManagerOptions, opts ...grpc.CallOption) (*DeviceManagerList, error)
	UpdateDeviceManager(ctx context.Context, in *DeviceManager, opts ...grpc.CallOption) (*DeviceManager, error)
	DeleteDeviceManager(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error)
	GetCoreCondition(ctx context.Context, in *Condition, opts ...grpc.CallOption) (*corev1.Condition, error)
}

type mainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMainServiceClient(cc grpc.ClientConnInterface) MainServiceClient {
	return &mainServiceClient{cc}
}

func (c *mainServiceClient) GetClusterConfig(ctx context.Context, in *GetClusterConfigRequest, opts ...grpc.CallOption) (*ClusterConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterConfig)
	err := c.cc.Invoke(ctx, MainService_GetClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateClusterConfig(ctx context.Context, in *ClusterConfig, opts ...grpc.CallOption) (*ClusterConfig, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterConfig)
	err := c.cc.Invoke(ctx, MainService_UpdateClusterConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) CreateCollectorExporter(ctx context.Context, in *CollectorExporter, opts ...grpc.CallOption) (*CollectorExporter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectorExporter)
	err := c.cc.Invoke(ctx, MainService_CreateCollectorExporter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetCollectorExporter(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*CollectorExporter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectorExporter)
	err := c.cc.Invoke(ctx, MainService_GetCollectorExporter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListCollectorExporter(ctx context.Context, in *ListCollectorExporterOptions, opts ...grpc.CallOption) (*CollectorExporterList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectorExporterList)
	err := c.cc.Invoke(ctx, MainService_ListCollectorExporter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateCollectorExporter(ctx context.Context, in *CollectorExporter, opts ...grpc.CallOption) (*CollectorExporter, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectorExporter)
	err := c.cc.Invoke(ctx, MainService_UpdateCollectorExporter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeleteCollectorExporter(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, MainService_DeleteCollectorExporter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetDNSProvider(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*DNSProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSProvider)
	err := c.cc.Invoke(ctx, MainService_GetDNSProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListDNSProvider(ctx context.Context, in *ListDNSProviderOptions, opts ...grpc.CallOption) (*DNSProviderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSProviderList)
	err := c.cc.Invoke(ctx, MainService_ListDNSProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateDNSProvider(ctx context.Context, in *DNSProvider, opts ...grpc.CallOption) (*DNSProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DNSProvider)
	err := c.cc.Invoke(ctx, MainService_UpdateDNSProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetCertificate(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Certificate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Certificate)
	err := c.cc.Invoke(ctx, MainService_GetCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateCertificate(ctx context.Context, in *Certificate, opts ...grpc.CallOption) (*Certificate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Certificate)
	err := c.cc.Invoke(ctx, MainService_UpdateCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListCertificate(ctx context.Context, in *ListCertificateOptions, opts ...grpc.CallOption) (*CertificateList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateList)
	err := c.cc.Invoke(ctx, MainService_ListCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) IssueCertificate(ctx context.Context, in *IssueCertificateRequest, opts ...grpc.CallOption) (*IssueCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueCertificateResponse)
	err := c.cc.Invoke(ctx, MainService_IssueCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetCertificateIssuer(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*CertificateIssuer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateIssuer)
	err := c.cc.Invoke(ctx, MainService_GetCertificateIssuer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListCertificateIssuer(ctx context.Context, in *ListCertificateIssuerOptions, opts ...grpc.CallOption) (*CertificateIssuerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateIssuerList)
	err := c.cc.Invoke(ctx, MainService_ListCertificateIssuer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateCertificateIssuer(ctx context.Context, in *CertificateIssuer, opts ...grpc.CallOption) (*CertificateIssuer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateIssuer)
	err := c.cc.Invoke(ctx, MainService_UpdateCertificateIssuer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) CreateDirectoryProvider(ctx context.Context, in *DirectoryProvider, opts ...grpc.CallOption) (*DirectoryProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectoryProvider)
	err := c.cc.Invoke(ctx, MainService_CreateDirectoryProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetDirectoryProvider(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*DirectoryProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectoryProvider)
	err := c.cc.Invoke(ctx, MainService_GetDirectoryProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListDirectoryProvider(ctx context.Context, in *ListDirectoryProviderOptions, opts ...grpc.CallOption) (*DirectoryProviderList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectoryProviderList)
	err := c.cc.Invoke(ctx, MainService_ListDirectoryProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateDirectoryProvider(ctx context.Context, in *DirectoryProvider, opts ...grpc.CallOption) (*DirectoryProvider, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectoryProvider)
	err := c.cc.Invoke(ctx, MainService_UpdateDirectoryProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeleteDirectoryProvider(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, MainService_DeleteDirectoryProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GenerateDirectoryProviderCredential(ctx context.Context, in *GenerateDirectoryProviderCredentialRequest, opts ...grpc.CallOption) (*GenerateDirectoryProviderCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateDirectoryProviderCredentialResponse)
	err := c.cc.Invoke(ctx, MainService_GenerateDirectoryProviderCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListDirectoryProviderUser(ctx context.Context, in *ListDirectoryProviderUserOptions, opts ...grpc.CallOption) (*DirectoryProviderUserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectoryProviderUserList)
	err := c.cc.Invoke(ctx, MainService_ListDirectoryProviderUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListDirectoryProviderGroup(ctx context.Context, in *ListDirectoryProviderGroupOptions, opts ...grpc.CallOption) (*DirectoryProviderGroupList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirectoryProviderGroupList)
	err := c.cc.Invoke(ctx, MainService_ListDirectoryProviderGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) SynchronizeDirectoryProvider(ctx context.Context, in *SynchronizeDirectoryProviderRequest, opts ...grpc.CallOption) (*SynchronizeDirectoryProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SynchronizeDirectoryProviderResponse)
	err := c.cc.Invoke(ctx, MainService_SynchronizeDirectoryProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) CreateSecret(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, MainService_CreateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListSecret(ctx context.Context, in *ListSecretOptions, opts ...grpc.CallOption) (*SecretList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretList)
	err := c.cc.Invoke(ctx, MainService_ListSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeleteSecret(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, MainService_DeleteSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetSecret(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, MainService_GetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateSecret(ctx context.Context, in *Secret, opts ...grpc.CallOption) (*Secret, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Secret)
	err := c.cc.Invoke(ctx, MainService_UpdateSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetSecretStore(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*SecretStore, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretStore)
	err := c.cc.Invoke(ctx, MainService_GetSecretStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListSecretStore(ctx context.Context, in *ListSecretStoreOptions, opts ...grpc.CallOption) (*SecretStoreList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretStoreList)
	err := c.cc.Invoke(ctx, MainService_ListSecretStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateSecretStore(ctx context.Context, in *SecretStore, opts ...grpc.CallOption) (*SecretStore, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecretStore)
	err := c.cc.Invoke(ctx, MainService_UpdateSecretStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) CreateDeviceManager(ctx context.Context, in *DeviceManager, opts ...grpc.CallOption) (*DeviceManager, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceManager)
	err := c.cc.Invoke(ctx, MainService_CreateDeviceManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetDeviceManager(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*DeviceManager, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceManager)
	err := c.cc.Invoke(ctx, MainService_GetDeviceManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListDeviceManager(ctx context.Context, in *ListDeviceManagerOptions, opts ...grpc.CallOption) (*DeviceManagerList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceManagerList)
	err := c.cc.Invoke(ctx, MainService_ListDeviceManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateDeviceManager(ctx context.Context, in *DeviceManager, opts ...grpc.CallOption) (*DeviceManager, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceManager)
	err := c.cc.Invoke(ctx, MainService_UpdateDeviceManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeleteDeviceManager(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, MainService_DeleteDeviceManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetCoreCondition(ctx context.Context, in *Condition, opts ...grpc.CallOption) (*corev1.Condition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(corev1.Condition)
	err := c.cc.Invoke(ctx, MainService_GetCoreCondition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MainServiceServer is the server API for MainService service.
// All implementations must embed UnimplementedMainServiceServer
// for forward compatibility.
type MainServiceServer interface {
	// GetClusterConfig gets the Cluster Configuration.
	GetClusterConfig(context.Context, *GetClusterConfigRequest) (*ClusterConfig, error)
	// UpdateConfig updates the Cluster Configuration.
	UpdateClusterConfig(context.Context, *ClusterConfig) (*ClusterConfig, error)
	CreateCollectorExporter(context.Context, *CollectorExporter) (*CollectorExporter, error)
	GetCollectorExporter(context.Context, *metav1.GetOptions) (*CollectorExporter, error)
	ListCollectorExporter(context.Context, *ListCollectorExporterOptions) (*CollectorExporterList, error)
	UpdateCollectorExporter(context.Context, *CollectorExporter) (*CollectorExporter, error)
	DeleteCollectorExporter(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error)
	// rpc CreateDNSProvider(DNSProvider) returns (DNSProvider) {}
	GetDNSProvider(context.Context, *metav1.GetOptions) (*DNSProvider, error)
	ListDNSProvider(context.Context, *ListDNSProviderOptions) (*DNSProviderList, error)
	UpdateDNSProvider(context.Context, *DNSProvider) (*DNSProvider, error)
	// rpc CreateCertificate(Certificate) returns (Certificate) {}
	GetCertificate(context.Context, *metav1.GetOptions) (*Certificate, error)
	UpdateCertificate(context.Context, *Certificate) (*Certificate, error)
	ListCertificate(context.Context, *ListCertificateOptions) (*CertificateList, error)
	IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error)
	// rpc CreateCertificateIssuer(CertificateIssuer) returns (CertificateIssuer)
	// {}
	GetCertificateIssuer(context.Context, *metav1.GetOptions) (*CertificateIssuer, error)
	ListCertificateIssuer(context.Context, *ListCertificateIssuerOptions) (*CertificateIssuerList, error)
	UpdateCertificateIssuer(context.Context, *CertificateIssuer) (*CertificateIssuer, error)
	CreateDirectoryProvider(context.Context, *DirectoryProvider) (*DirectoryProvider, error)
	GetDirectoryProvider(context.Context, *metav1.GetOptions) (*DirectoryProvider, error)
	ListDirectoryProvider(context.Context, *ListDirectoryProviderOptions) (*DirectoryProviderList, error)
	UpdateDirectoryProvider(context.Context, *DirectoryProvider) (*DirectoryProvider, error)
	DeleteDirectoryProvider(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error)
	GenerateDirectoryProviderCredential(context.Context, *GenerateDirectoryProviderCredentialRequest) (*GenerateDirectoryProviderCredentialResponse, error)
	ListDirectoryProviderUser(context.Context, *ListDirectoryProviderUserOptions) (*DirectoryProviderUserList, error)
	ListDirectoryProviderGroup(context.Context, *ListDirectoryProviderGroupOptions) (*DirectoryProviderGroupList, error)
	SynchronizeDirectoryProvider(context.Context, *SynchronizeDirectoryProviderRequest) (*SynchronizeDirectoryProviderResponse, error)
	// CreateSecret creates a Secret
	CreateSecret(context.Context, *Secret) (*Secret, error)
	// ListSecret lists Secrets
	ListSecret(context.Context, *ListSecretOptions) (*SecretList, error)
	// DeleteSecret deletes a Secret
	DeleteSecret(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error)
	// GetSecret retrieves a specific Secret
	GetSecret(context.Context, *metav1.GetOptions) (*Secret, error)
	// UpdateSecret creates a Secret
	UpdateSecret(context.Context, *Secret) (*Secret, error)
	// rpc CreateSecretStore(SecretStore) returns (SecretStore) {}
	GetSecretStore(context.Context, *metav1.GetOptions) (*SecretStore, error)
	ListSecretStore(context.Context, *ListSecretStoreOptions) (*SecretStoreList, error)
	UpdateSecretStore(context.Context, *SecretStore) (*SecretStore, error)
	CreateDeviceManager(context.Context, *DeviceManager) (*DeviceManager, error)
	GetDeviceManager(context.Context, *metav1.GetOptions) (*DeviceManager, error)
	ListDeviceManager(context.Context, *ListDeviceManagerOptions) (*DeviceManagerList, error)
	UpdateDeviceManager(context.Context, *DeviceManager) (*DeviceManager, error)
	DeleteDeviceManager(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error)
	GetCoreCondition(context.Context, *Condition) (*corev1.Condition, error)
	mustEmbedUnimplementedMainServiceServer()
}

// UnimplementedMainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMainServiceServer struct{}

func (UnimplementedMainServiceServer) GetClusterConfig(context.Context, *GetClusterConfigRequest) (*ClusterConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterConfig not implemented")
}
func (UnimplementedMainServiceServer) UpdateClusterConfig(context.Context, *ClusterConfig) (*ClusterConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClusterConfig not implemented")
}
func (UnimplementedMainServiceServer) CreateCollectorExporter(context.Context, *CollectorExporter) (*CollectorExporter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollectorExporter not implemented")
}
func (UnimplementedMainServiceServer) GetCollectorExporter(context.Context, *metav1.GetOptions) (*CollectorExporter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectorExporter not implemented")
}
func (UnimplementedMainServiceServer) ListCollectorExporter(context.Context, *ListCollectorExporterOptions) (*CollectorExporterList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollectorExporter not implemented")
}
func (UnimplementedMainServiceServer) UpdateCollectorExporter(context.Context, *CollectorExporter) (*CollectorExporter, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollectorExporter not implemented")
}
func (UnimplementedMainServiceServer) DeleteCollectorExporter(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollectorExporter not implemented")
}
func (UnimplementedMainServiceServer) GetDNSProvider(context.Context, *metav1.GetOptions) (*DNSProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDNSProvider not implemented")
}
func (UnimplementedMainServiceServer) ListDNSProvider(context.Context, *ListDNSProviderOptions) (*DNSProviderList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDNSProvider not implemented")
}
func (UnimplementedMainServiceServer) UpdateDNSProvider(context.Context, *DNSProvider) (*DNSProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDNSProvider not implemented")
}
func (UnimplementedMainServiceServer) GetCertificate(context.Context, *metav1.GetOptions) (*Certificate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedMainServiceServer) UpdateCertificate(context.Context, *Certificate) (*Certificate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCertificate not implemented")
}
func (UnimplementedMainServiceServer) ListCertificate(context.Context, *ListCertificateOptions) (*CertificateList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCertificate not implemented")
}
func (UnimplementedMainServiceServer) IssueCertificate(context.Context, *IssueCertificateRequest) (*IssueCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueCertificate not implemented")
}
func (UnimplementedMainServiceServer) GetCertificateIssuer(context.Context, *metav1.GetOptions) (*CertificateIssuer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCertificateIssuer not implemented")
}
func (UnimplementedMainServiceServer) ListCertificateIssuer(context.Context, *ListCertificateIssuerOptions) (*CertificateIssuerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCertificateIssuer not implemented")
}
func (UnimplementedMainServiceServer) UpdateCertificateIssuer(context.Context, *CertificateIssuer) (*CertificateIssuer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCertificateIssuer not implemented")
}
func (UnimplementedMainServiceServer) CreateDirectoryProvider(context.Context, *DirectoryProvider) (*DirectoryProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDirectoryProvider not implemented")
}
func (UnimplementedMainServiceServer) GetDirectoryProvider(context.Context, *metav1.GetOptions) (*DirectoryProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDirectoryProvider not implemented")
}
func (UnimplementedMainServiceServer) ListDirectoryProvider(context.Context, *ListDirectoryProviderOptions) (*DirectoryProviderList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectoryProvider not implemented")
}
func (UnimplementedMainServiceServer) UpdateDirectoryProvider(context.Context, *DirectoryProvider) (*DirectoryProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDirectoryProvider not implemented")
}
func (UnimplementedMainServiceServer) DeleteDirectoryProvider(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDirectoryProvider not implemented")
}
func (UnimplementedMainServiceServer) GenerateDirectoryProviderCredential(context.Context, *GenerateDirectoryProviderCredentialRequest) (*GenerateDirectoryProviderCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateDirectoryProviderCredential not implemented")
}
func (UnimplementedMainServiceServer) ListDirectoryProviderUser(context.Context, *ListDirectoryProviderUserOptions) (*DirectoryProviderUserList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectoryProviderUser not implemented")
}
func (UnimplementedMainServiceServer) ListDirectoryProviderGroup(context.Context, *ListDirectoryProviderGroupOptions) (*DirectoryProviderGroupList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectoryProviderGroup not implemented")
}
func (UnimplementedMainServiceServer) SynchronizeDirectoryProvider(context.Context, *SynchronizeDirectoryProviderRequest) (*SynchronizeDirectoryProviderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SynchronizeDirectoryProvider not implemented")
}
func (UnimplementedMainServiceServer) CreateSecret(context.Context, *Secret) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSecret not implemented")
}
func (UnimplementedMainServiceServer) ListSecret(context.Context, *ListSecretOptions) (*SecretList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecret not implemented")
}
func (UnimplementedMainServiceServer) DeleteSecret(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSecret not implemented")
}
func (UnimplementedMainServiceServer) GetSecret(context.Context, *metav1.GetOptions) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedMainServiceServer) UpdateSecret(context.Context, *Secret) (*Secret, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSecret not implemented")
}
func (UnimplementedMainServiceServer) GetSecretStore(context.Context, *metav1.GetOptions) (*SecretStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecretStore not implemented")
}
func (UnimplementedMainServiceServer) ListSecretStore(context.Context, *ListSecretStoreOptions) (*SecretStoreList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecretStore not implemented")
}
func (UnimplementedMainServiceServer) UpdateSecretStore(context.Context, *SecretStore) (*SecretStore, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSecretStore not implemented")
}
func (UnimplementedMainServiceServer) CreateDeviceManager(context.Context, *DeviceManager) (*DeviceManager, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeviceManager not implemented")
}
func (UnimplementedMainServiceServer) GetDeviceManager(context.Context, *metav1.GetOptions) (*DeviceManager, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceManager not implemented")
}
func (UnimplementedMainServiceServer) ListDeviceManager(context.Context, *ListDeviceManagerOptions) (*DeviceManagerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeviceManager not implemented")
}
func (UnimplementedMainServiceServer) UpdateDeviceManager(context.Context, *DeviceManager) (*DeviceManager, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeviceManager not implemented")
}
func (UnimplementedMainServiceServer) DeleteDeviceManager(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeviceManager not implemented")
}
func (UnimplementedMainServiceServer) GetCoreCondition(context.Context, *Condition) (*corev1.Condition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCoreCondition not implemented")
}
func (UnimplementedMainServiceServer) mustEmbedUnimplementedMainServiceServer() {}
func (UnimplementedMainServiceServer) testEmbeddedByValue()                     {}

// UnsafeMainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MainServiceServer will
// result in compilation errors.
type UnsafeMainServiceServer interface {
	mustEmbedUnimplementedMainServiceServer()
}

func RegisterMainServiceServer(s grpc.ServiceRegistrar, srv MainServiceServer) {
	// If the following call pancis, it indicates UnimplementedMainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MainService_ServiceDesc, srv)
}

func _MainService_GetClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetClusterConfig(ctx, req.(*GetClusterConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateClusterConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateClusterConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateClusterConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateClusterConfig(ctx, req.(*ClusterConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_CreateCollectorExporter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectorExporter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).CreateCollectorExporter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_CreateCollectorExporter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).CreateCollectorExporter(ctx, req.(*CollectorExporter))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetCollectorExporter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetCollectorExporter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetCollectorExporter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetCollectorExporter(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListCollectorExporter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectorExporterOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListCollectorExporter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListCollectorExporter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListCollectorExporter(ctx, req.(*ListCollectorExporterOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateCollectorExporter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectorExporter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateCollectorExporter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateCollectorExporter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateCollectorExporter(ctx, req.(*CollectorExporter))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeleteCollectorExporter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeleteCollectorExporter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeleteCollectorExporter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeleteCollectorExporter(ctx, req.(*metav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetDNSProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetDNSProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetDNSProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetDNSProvider(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListDNSProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDNSProviderOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListDNSProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListDNSProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListDNSProvider(ctx, req.(*ListDNSProviderOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateDNSProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DNSProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateDNSProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateDNSProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateDNSProvider(ctx, req.(*DNSProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetCertificate(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Certificate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateCertificate(ctx, req.(*Certificate))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificateOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListCertificate(ctx, req.(*ListCertificateOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_IssueCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).IssueCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_IssueCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).IssueCertificate(ctx, req.(*IssueCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetCertificateIssuer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetCertificateIssuer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetCertificateIssuer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetCertificateIssuer(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListCertificateIssuer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificateIssuerOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListCertificateIssuer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListCertificateIssuer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListCertificateIssuer(ctx, req.(*ListCertificateIssuerOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateCertificateIssuer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateIssuer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateCertificateIssuer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateCertificateIssuer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateCertificateIssuer(ctx, req.(*CertificateIssuer))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_CreateDirectoryProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectoryProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).CreateDirectoryProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_CreateDirectoryProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).CreateDirectoryProvider(ctx, req.(*DirectoryProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetDirectoryProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetDirectoryProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetDirectoryProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetDirectoryProvider(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListDirectoryProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryProviderOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListDirectoryProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListDirectoryProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListDirectoryProvider(ctx, req.(*ListDirectoryProviderOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateDirectoryProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectoryProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateDirectoryProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateDirectoryProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateDirectoryProvider(ctx, req.(*DirectoryProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeleteDirectoryProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeleteDirectoryProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeleteDirectoryProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeleteDirectoryProvider(ctx, req.(*metav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GenerateDirectoryProviderCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateDirectoryProviderCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GenerateDirectoryProviderCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GenerateDirectoryProviderCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GenerateDirectoryProviderCredential(ctx, req.(*GenerateDirectoryProviderCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListDirectoryProviderUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryProviderUserOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListDirectoryProviderUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListDirectoryProviderUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListDirectoryProviderUser(ctx, req.(*ListDirectoryProviderUserOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListDirectoryProviderGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryProviderGroupOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListDirectoryProviderGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListDirectoryProviderGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListDirectoryProviderGroup(ctx, req.(*ListDirectoryProviderGroupOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_SynchronizeDirectoryProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SynchronizeDirectoryProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).SynchronizeDirectoryProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_SynchronizeDirectoryProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).SynchronizeDirectoryProvider(ctx, req.(*SynchronizeDirectoryProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_CreateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).CreateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_CreateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).CreateSecret(ctx, req.(*Secret))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListSecret(ctx, req.(*ListSecretOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeleteSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeleteSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeleteSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeleteSecret(ctx, req.(*metav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetSecret(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Secret)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateSecret(ctx, req.(*Secret))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetSecretStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetSecretStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetSecretStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetSecretStore(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListSecretStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretStoreOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListSecretStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListSecretStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListSecretStore(ctx, req.(*ListSecretStoreOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateSecretStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateSecretStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateSecretStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateSecretStore(ctx, req.(*SecretStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_CreateDeviceManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceManager)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).CreateDeviceManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_CreateDeviceManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).CreateDeviceManager(ctx, req.(*DeviceManager))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetDeviceManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetDeviceManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetDeviceManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetDeviceManager(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListDeviceManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceManagerOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListDeviceManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListDeviceManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListDeviceManager(ctx, req.(*ListDeviceManagerOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateDeviceManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceManager)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateDeviceManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateDeviceManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateDeviceManager(ctx, req.(*DeviceManager))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeleteDeviceManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeleteDeviceManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeleteDeviceManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeleteDeviceManager(ctx, req.(*metav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetCoreCondition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Condition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetCoreCondition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetCoreCondition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetCoreCondition(ctx, req.(*Condition))
	}
	return interceptor(ctx, in, info, handler)
}

// MainService_ServiceDesc is the grpc.ServiceDesc for MainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.main.enterprise.v1.MainService",
	HandlerType: (*MainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterConfig",
			Handler:    _MainService_GetClusterConfig_Handler,
		},
		{
			MethodName: "UpdateClusterConfig",
			Handler:    _MainService_UpdateClusterConfig_Handler,
		},
		{
			MethodName: "CreateCollectorExporter",
			Handler:    _MainService_CreateCollectorExporter_Handler,
		},
		{
			MethodName: "GetCollectorExporter",
			Handler:    _MainService_GetCollectorExporter_Handler,
		},
		{
			MethodName: "ListCollectorExporter",
			Handler:    _MainService_ListCollectorExporter_Handler,
		},
		{
			MethodName: "UpdateCollectorExporter",
			Handler:    _MainService_UpdateCollectorExporter_Handler,
		},
		{
			MethodName: "DeleteCollectorExporter",
			Handler:    _MainService_DeleteCollectorExporter_Handler,
		},
		{
			MethodName: "GetDNSProvider",
			Handler:    _MainService_GetDNSProvider_Handler,
		},
		{
			MethodName: "ListDNSProvider",
			Handler:    _MainService_ListDNSProvider_Handler,
		},
		{
			MethodName: "UpdateDNSProvider",
			Handler:    _MainService_UpdateDNSProvider_Handler,
		},
		{
			MethodName: "GetCertificate",
			Handler:    _MainService_GetCertificate_Handler,
		},
		{
			MethodName: "UpdateCertificate",
			Handler:    _MainService_UpdateCertificate_Handler,
		},
		{
			MethodName: "ListCertificate",
			Handler:    _MainService_ListCertificate_Handler,
		},
		{
			MethodName: "IssueCertificate",
			Handler:    _MainService_IssueCertificate_Handler,
		},
		{
			MethodName: "GetCertificateIssuer",
			Handler:    _MainService_GetCertificateIssuer_Handler,
		},
		{
			MethodName: "ListCertificateIssuer",
			Handler:    _MainService_ListCertificateIssuer_Handler,
		},
		{
			MethodName: "UpdateCertificateIssuer",
			Handler:    _MainService_UpdateCertificateIssuer_Handler,
		},
		{
			MethodName: "CreateDirectoryProvider",
			Handler:    _MainService_CreateDirectoryProvider_Handler,
		},
		{
			MethodName: "GetDirectoryProvider",
			Handler:    _MainService_GetDirectoryProvider_Handler,
		},
		{
			MethodName: "ListDirectoryProvider",
			Handler:    _MainService_ListDirectoryProvider_Handler,
		},
		{
			MethodName: "UpdateDirectoryProvider",
			Handler:    _MainService_UpdateDirectoryProvider_Handler,
		},
		{
			MethodName: "DeleteDirectoryProvider",
			Handler:    _MainService_DeleteDirectoryProvider_Handler,
		},
		{
			MethodName: "GenerateDirectoryProviderCredential",
			Handler:    _MainService_GenerateDirectoryProviderCredential_Handler,
		},
		{
			MethodName: "ListDirectoryProviderUser",
			Handler:    _MainService_ListDirectoryProviderUser_Handler,
		},
		{
			MethodName: "ListDirectoryProviderGroup",
			Handler:    _MainService_ListDirectoryProviderGroup_Handler,
		},
		{
			MethodName: "SynchronizeDirectoryProvider",
			Handler:    _MainService_SynchronizeDirectoryProvider_Handler,
		},
		{
			MethodName: "CreateSecret",
			Handler:    _MainService_CreateSecret_Handler,
		},
		{
			MethodName: "ListSecret",
			Handler:    _MainService_ListSecret_Handler,
		},
		{
			MethodName: "DeleteSecret",
			Handler:    _MainService_DeleteSecret_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _MainService_GetSecret_Handler,
		},
		{
			MethodName: "UpdateSecret",
			Handler:    _MainService_UpdateSecret_Handler,
		},
		{
			MethodName: "GetSecretStore",
			Handler:    _MainService_GetSecretStore_Handler,
		},
		{
			MethodName: "ListSecretStore",
			Handler:    _MainService_ListSecretStore_Handler,
		},
		{
			MethodName: "UpdateSecretStore",
			Handler:    _MainService_UpdateSecretStore_Handler,
		},
		{
			MethodName: "CreateDeviceManager",
			Handler:    _MainService_CreateDeviceManager_Handler,
		},
		{
			MethodName: "GetDeviceManager",
			Handler:    _MainService_GetDeviceManager_Handler,
		},
		{
			MethodName: "ListDeviceManager",
			Handler:    _MainService_ListDeviceManager_Handler,
		},
		{
			MethodName: "UpdateDeviceManager",
			Handler:    _MainService_UpdateDeviceManager_Handler,
		},
		{
			MethodName: "DeleteDeviceManager",
			Handler:    _MainService_DeleteDeviceManager_Handler,
		},
		{
			MethodName: "GetCoreCondition",
			Handler:    _MainService_GetCoreCondition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enterprisev1.proto",
}

const (
	PolicyPortalService_IsAuthorized_FullMethodName = "/octelium.api.main.enterprise.v1.PolicyPortalService/IsAuthorized"
)

// PolicyPortalServiceClient is the client API for PolicyPortalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyPortalServiceClient interface {
	IsAuthorized(ctx context.Context, in *IsAuthorizedRequest, opts ...grpc.CallOption) (*IsAuthorizedResponse, error)
}

type policyPortalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyPortalServiceClient(cc grpc.ClientConnInterface) PolicyPortalServiceClient {
	return &policyPortalServiceClient{cc}
}

func (c *policyPortalServiceClient) IsAuthorized(ctx context.Context, in *IsAuthorizedRequest, opts ...grpc.CallOption) (*IsAuthorizedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsAuthorizedResponse)
	err := c.cc.Invoke(ctx, PolicyPortalService_IsAuthorized_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyPortalServiceServer is the server API for PolicyPortalService service.
// All implementations must embed UnimplementedPolicyPortalServiceServer
// for forward compatibility.
type PolicyPortalServiceServer interface {
	IsAuthorized(context.Context, *IsAuthorizedRequest) (*IsAuthorizedResponse, error)
	mustEmbedUnimplementedPolicyPortalServiceServer()
}

// UnimplementedPolicyPortalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyPortalServiceServer struct{}

func (UnimplementedPolicyPortalServiceServer) IsAuthorized(context.Context, *IsAuthorizedRequest) (*IsAuthorizedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAuthorized not implemented")
}
func (UnimplementedPolicyPortalServiceServer) mustEmbedUnimplementedPolicyPortalServiceServer() {}
func (UnimplementedPolicyPortalServiceServer) testEmbeddedByValue()                             {}

// UnsafePolicyPortalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyPortalServiceServer will
// result in compilation errors.
type UnsafePolicyPortalServiceServer interface {
	mustEmbedUnimplementedPolicyPortalServiceServer()
}

func RegisterPolicyPortalServiceServer(s grpc.ServiceRegistrar, srv PolicyPortalServiceServer) {
	// If the following call pancis, it indicates UnimplementedPolicyPortalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyPortalService_ServiceDesc, srv)
}

func _PolicyPortalService_IsAuthorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthorizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyPortalServiceServer).IsAuthorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyPortalService_IsAuthorized_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyPortalServiceServer).IsAuthorized(ctx, req.(*IsAuthorizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyPortalService_ServiceDesc is the grpc.ServiceDesc for PolicyPortalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyPortalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.main.enterprise.v1.PolicyPortalService",
	HandlerType: (*PolicyPortalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAuthorized",
			Handler:    _PolicyPortalService_IsAuthorized_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enterprisev1.proto",
}

const (
	ClusterService_UpgradeCluster_FullMethodName = "/octelium.api.main.enterprise.v1.ClusterService/UpgradeCluster"
)

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterServiceClient interface {
	UpgradeCluster(ctx context.Context, in *UpgradeClusterRequest, opts ...grpc.CallOption) (*UpgradeClusterResponse, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) UpgradeCluster(ctx context.Context, in *UpgradeClusterRequest, opts ...grpc.CallOption) (*UpgradeClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeClusterResponse)
	err := c.cc.Invoke(ctx, ClusterService_UpgradeCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
// All implementations must embed UnimplementedClusterServiceServer
// for forward compatibility.
type ClusterServiceServer interface {
	UpgradeCluster(context.Context, *UpgradeClusterRequest) (*UpgradeClusterResponse, error)
	mustEmbedUnimplementedClusterServiceServer()
}

// UnimplementedClusterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterServiceServer struct{}

func (UnimplementedClusterServiceServer) UpgradeCluster(context.Context, *UpgradeClusterRequest) (*UpgradeClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpgradeCluster not implemented")
}
func (UnimplementedClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {}
func (UnimplementedClusterServiceServer) testEmbeddedByValue()                        {}

// UnsafeClusterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterServiceServer will
// result in compilation errors.
type UnsafeClusterServiceServer interface {
	mustEmbedUnimplementedClusterServiceServer()
}

func RegisterClusterServiceServer(s grpc.ServiceRegistrar, srv ClusterServiceServer) {
	// If the following call pancis, it indicates UnimplementedClusterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterService_ServiceDesc, srv)
}

func _ClusterService_UpgradeCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).UpgradeCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterService_UpgradeCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).UpgradeCluster(ctx, req.(*UpgradeClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterService_ServiceDesc is the grpc.ServiceDesc for ClusterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.main.enterprise.v1.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpgradeCluster",
			Handler:    _ClusterService_UpgradeCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "enterprisev1.proto",
}
