// Copyright (c) 2025-present Octelium Labs, LLC. All rights reserved.
//
// This software is licensed under the Octelium Enterprise Source-Available License.
// Commercial and production use is strictly prohibited without a valid
// Commercial Agreement from Octelium Labs, LLC.
//
// See the LICENSE file in the repository root for full license text.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: vaccessv1.proto

package vaccessv1

import (
	context "context"
	accessv1 "github.com/octelium/octelium/apis/main/accessv1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceService_GetPolicySummary_FullMethodName  = "/octelium.api.main.visibility.access.v1.ResourceService/GetPolicySummary"
	ResourceService_GetCatalogSummary_FullMethodName = "/octelium.api.main.visibility.access.v1.ResourceService/GetCatalogSummary"
	ResourceService_GetRequestSummary_FullMethodName = "/octelium.api.main.visibility.access.v1.ResourceService/GetRequestSummary"
	ResourceService_GetReviewSummary_FullMethodName  = "/octelium.api.main.visibility.access.v1.ResourceService/GetReviewSummary"
	ResourceService_ListPolicy_FullMethodName        = "/octelium.api.main.visibility.access.v1.ResourceService/ListPolicy"
	ResourceService_ListCatalog_FullMethodName       = "/octelium.api.main.visibility.access.v1.ResourceService/ListCatalog"
	ResourceService_ListRequest_FullMethodName       = "/octelium.api.main.visibility.access.v1.ResourceService/ListRequest"
	ResourceService_ListReview_FullMethodName        = "/octelium.api.main.visibility.access.v1.ResourceService/ListReview"
)

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceServiceClient interface {
	GetPolicySummary(ctx context.Context, in *GetPolicySummaryRequest, opts ...grpc.CallOption) (*GetPolicySummaryResponse, error)
	GetCatalogSummary(ctx context.Context, in *GetCatalogSummaryRequest, opts ...grpc.CallOption) (*GetCatalogSummaryResponse, error)
	GetRequestSummary(ctx context.Context, in *GetRequestSummaryRequest, opts ...grpc.CallOption) (*GetRequestSummaryResponse, error)
	GetReviewSummary(ctx context.Context, in *GetReviewSummaryRequest, opts ...grpc.CallOption) (*GetReviewSummaryResponse, error)
	ListPolicy(ctx context.Context, in *ListPolicyOptions, opts ...grpc.CallOption) (*accessv1.PolicyList, error)
	ListCatalog(ctx context.Context, in *ListCatalogOptions, opts ...grpc.CallOption) (*accessv1.CatalogList, error)
	ListRequest(ctx context.Context, in *ListRequestOptions, opts ...grpc.CallOption) (*accessv1.RequestList, error)
	ListReview(ctx context.Context, in *ListReviewOptions, opts ...grpc.CallOption) (*accessv1.ReviewList, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) GetPolicySummary(ctx context.Context, in *GetPolicySummaryRequest, opts ...grpc.CallOption) (*GetPolicySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicySummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetPolicySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetCatalogSummary(ctx context.Context, in *GetCatalogSummaryRequest, opts ...grpc.CallOption) (*GetCatalogSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatalogSummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetCatalogSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetRequestSummary(ctx context.Context, in *GetRequestSummaryRequest, opts ...grpc.CallOption) (*GetRequestSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRequestSummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetRequestSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetReviewSummary(ctx context.Context, in *GetReviewSummaryRequest, opts ...grpc.CallOption) (*GetReviewSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewSummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetReviewSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListPolicy(ctx context.Context, in *ListPolicyOptions, opts ...grpc.CallOption) (*accessv1.PolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.PolicyList)
	err := c.cc.Invoke(ctx, ResourceService_ListPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListCatalog(ctx context.Context, in *ListCatalogOptions, opts ...grpc.CallOption) (*accessv1.CatalogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.CatalogList)
	err := c.cc.Invoke(ctx, ResourceService_ListCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListRequest(ctx context.Context, in *ListRequestOptions, opts ...grpc.CallOption) (*accessv1.RequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.RequestList)
	err := c.cc.Invoke(ctx, ResourceService_ListRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListReview(ctx context.Context, in *ListReviewOptions, opts ...grpc.CallOption) (*accessv1.ReviewList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.ReviewList)
	err := c.cc.Invoke(ctx, ResourceService_ListReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility.
type ResourceServiceServer interface {
	GetPolicySummary(context.Context, *GetPolicySummaryRequest) (*GetPolicySummaryResponse, error)
	GetCatalogSummary(context.Context, *GetCatalogSummaryRequest) (*GetCatalogSummaryResponse, error)
	GetRequestSummary(context.Context, *GetRequestSummaryRequest) (*GetRequestSummaryResponse, error)
	GetReviewSummary(context.Context, *GetReviewSummaryRequest) (*GetReviewSummaryResponse, error)
	ListPolicy(context.Context, *ListPolicyOptions) (*accessv1.PolicyList, error)
	ListCatalog(context.Context, *ListCatalogOptions) (*accessv1.CatalogList, error)
	ListRequest(context.Context, *ListRequestOptions) (*accessv1.RequestList, error)
	ListReview(context.Context, *ListReviewOptions) (*accessv1.ReviewList, error)
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceServiceServer struct{}

func (UnimplementedResourceServiceServer) GetPolicySummary(context.Context, *GetPolicySummaryRequest) (*GetPolicySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicySummary not implemented")
}
func (UnimplementedResourceServiceServer) GetCatalogSummary(context.Context, *GetCatalogSummaryRequest) (*GetCatalogSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatalogSummary not implemented")
}
func (UnimplementedResourceServiceServer) GetRequestSummary(context.Context, *GetRequestSummaryRequest) (*GetRequestSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequestSummary not implemented")
}
func (UnimplementedResourceServiceServer) GetReviewSummary(context.Context, *GetReviewSummaryRequest) (*GetReviewSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviewSummary not implemented")
}
func (UnimplementedResourceServiceServer) ListPolicy(context.Context, *ListPolicyOptions) (*accessv1.PolicyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPolicy not implemented")
}
func (UnimplementedResourceServiceServer) ListCatalog(context.Context, *ListCatalogOptions) (*accessv1.CatalogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCatalog not implemented")
}
func (UnimplementedResourceServiceServer) ListRequest(context.Context, *ListRequestOptions) (*accessv1.RequestList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRequest not implemented")
}
func (UnimplementedResourceServiceServer) ListReview(context.Context, *ListReviewOptions) (*accessv1.ReviewList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReview not implemented")
}
func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {}
func (UnimplementedResourceServiceServer) testEmbeddedByValue()                         {}

// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServiceServer will
// result in compilation errors.
type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceService_ServiceDesc, srv)
}

func _ResourceService_GetPolicySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetPolicySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetPolicySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetPolicySummary(ctx, req.(*GetPolicySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetCatalogSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetCatalogSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetCatalogSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetCatalogSummary(ctx, req.(*GetCatalogSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetRequestSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetRequestSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetRequestSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetRequestSummary(ctx, req.(*GetRequestSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetReviewSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetReviewSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetReviewSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetReviewSummary(ctx, req.(*GetReviewSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPolicyOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListPolicy(ctx, req.(*ListPolicyOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatalogOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListCatalog(ctx, req.(*ListCatalogOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequestOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListRequest(ctx, req.(*ListRequestOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListReview(ctx, req.(*ListReviewOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.main.visibility.access.v1.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPolicySummary",
			Handler:    _ResourceService_GetPolicySummary_Handler,
		},
		{
			MethodName: "GetCatalogSummary",
			Handler:    _ResourceService_GetCatalogSummary_Handler,
		},
		{
			MethodName: "GetRequestSummary",
			Handler:    _ResourceService_GetRequestSummary_Handler,
		},
		{
			MethodName: "GetReviewSummary",
			Handler:    _ResourceService_GetReviewSummary_Handler,
		},
		{
			MethodName: "ListPolicy",
			Handler:    _ResourceService_ListPolicy_Handler,
		},
		{
			MethodName: "ListCatalog",
			Handler:    _ResourceService_ListCatalog_Handler,
		},
		{
			MethodName: "ListRequest",
			Handler:    _ResourceService_ListRequest_Handler,
		},
		{
			MethodName: "ListReview",
			Handler:    _ResourceService_ListReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vaccessv1.proto",
}
