// Copyright (c) 2025-present Octelium Labs, LLC. All rights reserved.
//
// This software is licensed under the Octelium Enterprise Source-Available License.
// Commercial and production use is strictly prohibited without a valid
// Commercial Agreement from Octelium Labs, LLC.
//
// See the LICENSE file in the repository root for full license text.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: vaccessv1.proto

package vaccessv1

import (
	context "context"
	accessv1 "github.com/octelium/octelium/apis/main/accessv1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ResourceService_GetPolicySummary_FullMethodName              = "/octelium.api.main.visibility.access.v1.ResourceService/GetPolicySummary"
	ResourceService_GetCatalogSummary_FullMethodName             = "/octelium.api.main.visibility.access.v1.ResourceService/GetCatalogSummary"
	ResourceService_GetRequestSummary_FullMethodName             = "/octelium.api.main.visibility.access.v1.ResourceService/GetRequestSummary"
	ResourceService_GetReviewSummary_FullMethodName              = "/octelium.api.main.visibility.access.v1.ResourceService/GetReviewSummary"
	ResourceService_GetSecretSummary_FullMethodName              = "/octelium.api.main.visibility.access.v1.ResourceService/GetSecretSummary"
	ResourceService_GetIntegrationSummary_FullMethodName         = "/octelium.api.main.visibility.access.v1.ResourceService/GetIntegrationSummary"
	ResourceService_GetIntegrationIdentitySummary_FullMethodName = "/octelium.api.main.visibility.access.v1.ResourceService/GetIntegrationIdentitySummary"
	ResourceService_GetIntegrationBindingSummary_FullMethodName  = "/octelium.api.main.visibility.access.v1.ResourceService/GetIntegrationBindingSummary"
	ResourceService_ListPolicy_FullMethodName                    = "/octelium.api.main.visibility.access.v1.ResourceService/ListPolicy"
	ResourceService_ListCatalog_FullMethodName                   = "/octelium.api.main.visibility.access.v1.ResourceService/ListCatalog"
	ResourceService_ListRequest_FullMethodName                   = "/octelium.api.main.visibility.access.v1.ResourceService/ListRequest"
	ResourceService_ListReview_FullMethodName                    = "/octelium.api.main.visibility.access.v1.ResourceService/ListReview"
	ResourceService_ListSecret_FullMethodName                    = "/octelium.api.main.visibility.access.v1.ResourceService/ListSecret"
	ResourceService_ListIntegration_FullMethodName               = "/octelium.api.main.visibility.access.v1.ResourceService/ListIntegration"
	ResourceService_ListIntegrationIdentity_FullMethodName       = "/octelium.api.main.visibility.access.v1.ResourceService/ListIntegrationIdentity"
	ResourceService_ListIntegrationBinding_FullMethodName        = "/octelium.api.main.visibility.access.v1.ResourceService/ListIntegrationBinding"
)

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceServiceClient interface {
	GetPolicySummary(ctx context.Context, in *GetPolicySummaryRequest, opts ...grpc.CallOption) (*GetPolicySummaryResponse, error)
	GetCatalogSummary(ctx context.Context, in *GetCatalogSummaryRequest, opts ...grpc.CallOption) (*GetCatalogSummaryResponse, error)
	GetRequestSummary(ctx context.Context, in *GetRequestSummaryRequest, opts ...grpc.CallOption) (*GetRequestSummaryResponse, error)
	GetReviewSummary(ctx context.Context, in *GetReviewSummaryRequest, opts ...grpc.CallOption) (*GetReviewSummaryResponse, error)
	GetSecretSummary(ctx context.Context, in *GetSecretSummaryRequest, opts ...grpc.CallOption) (*GetSecretSummaryResponse, error)
	GetIntegrationSummary(ctx context.Context, in *GetIntegrationSummaryRequest, opts ...grpc.CallOption) (*GetIntegrationSummaryResponse, error)
	GetIntegrationIdentitySummary(ctx context.Context, in *GetIntegrationIdentitySummaryRequest, opts ...grpc.CallOption) (*GetIntegrationIdentitySummaryResponse, error)
	GetIntegrationBindingSummary(ctx context.Context, in *GetIntegrationBindingSummaryRequest, opts ...grpc.CallOption) (*GetIntegrationBindingSummaryResponse, error)
	ListPolicy(ctx context.Context, in *ListPolicyOptions, opts ...grpc.CallOption) (*accessv1.PolicyList, error)
	ListCatalog(ctx context.Context, in *ListCatalogOptions, opts ...grpc.CallOption) (*accessv1.CatalogList, error)
	ListRequest(ctx context.Context, in *ListRequestOptions, opts ...grpc.CallOption) (*accessv1.RequestList, error)
	ListReview(ctx context.Context, in *ListReviewOptions, opts ...grpc.CallOption) (*accessv1.ReviewList, error)
	ListSecret(ctx context.Context, in *ListSecretOptions, opts ...grpc.CallOption) (*accessv1.SecretList, error)
	ListIntegration(ctx context.Context, in *ListIntegrationOptions, opts ...grpc.CallOption) (*accessv1.IntegrationList, error)
	ListIntegrationIdentity(ctx context.Context, in *ListIntegrationIdentityOptions, opts ...grpc.CallOption) (*accessv1.IntegrationIdentityList, error)
	ListIntegrationBinding(ctx context.Context, in *ListIntegrationBindingOptions, opts ...grpc.CallOption) (*accessv1.IntegrationBindingList, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) GetPolicySummary(ctx context.Context, in *GetPolicySummaryRequest, opts ...grpc.CallOption) (*GetPolicySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicySummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetPolicySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetCatalogSummary(ctx context.Context, in *GetCatalogSummaryRequest, opts ...grpc.CallOption) (*GetCatalogSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCatalogSummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetCatalogSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetRequestSummary(ctx context.Context, in *GetRequestSummaryRequest, opts ...grpc.CallOption) (*GetRequestSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRequestSummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetRequestSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetReviewSummary(ctx context.Context, in *GetReviewSummaryRequest, opts ...grpc.CallOption) (*GetReviewSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReviewSummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetReviewSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetSecretSummary(ctx context.Context, in *GetSecretSummaryRequest, opts ...grpc.CallOption) (*GetSecretSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecretSummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetSecretSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetIntegrationSummary(ctx context.Context, in *GetIntegrationSummaryRequest, opts ...grpc.CallOption) (*GetIntegrationSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIntegrationSummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetIntegrationSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetIntegrationIdentitySummary(ctx context.Context, in *GetIntegrationIdentitySummaryRequest, opts ...grpc.CallOption) (*GetIntegrationIdentitySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIntegrationIdentitySummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetIntegrationIdentitySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) GetIntegrationBindingSummary(ctx context.Context, in *GetIntegrationBindingSummaryRequest, opts ...grpc.CallOption) (*GetIntegrationBindingSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIntegrationBindingSummaryResponse)
	err := c.cc.Invoke(ctx, ResourceService_GetIntegrationBindingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListPolicy(ctx context.Context, in *ListPolicyOptions, opts ...grpc.CallOption) (*accessv1.PolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.PolicyList)
	err := c.cc.Invoke(ctx, ResourceService_ListPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListCatalog(ctx context.Context, in *ListCatalogOptions, opts ...grpc.CallOption) (*accessv1.CatalogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.CatalogList)
	err := c.cc.Invoke(ctx, ResourceService_ListCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListRequest(ctx context.Context, in *ListRequestOptions, opts ...grpc.CallOption) (*accessv1.RequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.RequestList)
	err := c.cc.Invoke(ctx, ResourceService_ListRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListReview(ctx context.Context, in *ListReviewOptions, opts ...grpc.CallOption) (*accessv1.ReviewList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.ReviewList)
	err := c.cc.Invoke(ctx, ResourceService_ListReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListSecret(ctx context.Context, in *ListSecretOptions, opts ...grpc.CallOption) (*accessv1.SecretList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.SecretList)
	err := c.cc.Invoke(ctx, ResourceService_ListSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListIntegration(ctx context.Context, in *ListIntegrationOptions, opts ...grpc.CallOption) (*accessv1.IntegrationList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.IntegrationList)
	err := c.cc.Invoke(ctx, ResourceService_ListIntegration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListIntegrationIdentity(ctx context.Context, in *ListIntegrationIdentityOptions, opts ...grpc.CallOption) (*accessv1.IntegrationIdentityList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.IntegrationIdentityList)
	err := c.cc.Invoke(ctx, ResourceService_ListIntegrationIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) ListIntegrationBinding(ctx context.Context, in *ListIntegrationBindingOptions, opts ...grpc.CallOption) (*accessv1.IntegrationBindingList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(accessv1.IntegrationBindingList)
	err := c.cc.Invoke(ctx, ResourceService_ListIntegrationBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility.
type ResourceServiceServer interface {
	GetPolicySummary(context.Context, *GetPolicySummaryRequest) (*GetPolicySummaryResponse, error)
	GetCatalogSummary(context.Context, *GetCatalogSummaryRequest) (*GetCatalogSummaryResponse, error)
	GetRequestSummary(context.Context, *GetRequestSummaryRequest) (*GetRequestSummaryResponse, error)
	GetReviewSummary(context.Context, *GetReviewSummaryRequest) (*GetReviewSummaryResponse, error)
	GetSecretSummary(context.Context, *GetSecretSummaryRequest) (*GetSecretSummaryResponse, error)
	GetIntegrationSummary(context.Context, *GetIntegrationSummaryRequest) (*GetIntegrationSummaryResponse, error)
	GetIntegrationIdentitySummary(context.Context, *GetIntegrationIdentitySummaryRequest) (*GetIntegrationIdentitySummaryResponse, error)
	GetIntegrationBindingSummary(context.Context, *GetIntegrationBindingSummaryRequest) (*GetIntegrationBindingSummaryResponse, error)
	ListPolicy(context.Context, *ListPolicyOptions) (*accessv1.PolicyList, error)
	ListCatalog(context.Context, *ListCatalogOptions) (*accessv1.CatalogList, error)
	ListRequest(context.Context, *ListRequestOptions) (*accessv1.RequestList, error)
	ListReview(context.Context, *ListReviewOptions) (*accessv1.ReviewList, error)
	ListSecret(context.Context, *ListSecretOptions) (*accessv1.SecretList, error)
	ListIntegration(context.Context, *ListIntegrationOptions) (*accessv1.IntegrationList, error)
	ListIntegrationIdentity(context.Context, *ListIntegrationIdentityOptions) (*accessv1.IntegrationIdentityList, error)
	ListIntegrationBinding(context.Context, *ListIntegrationBindingOptions) (*accessv1.IntegrationBindingList, error)
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResourceServiceServer struct{}

func (UnimplementedResourceServiceServer) GetPolicySummary(context.Context, *GetPolicySummaryRequest) (*GetPolicySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicySummary not implemented")
}
func (UnimplementedResourceServiceServer) GetCatalogSummary(context.Context, *GetCatalogSummaryRequest) (*GetCatalogSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatalogSummary not implemented")
}
func (UnimplementedResourceServiceServer) GetRequestSummary(context.Context, *GetRequestSummaryRequest) (*GetRequestSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequestSummary not implemented")
}
func (UnimplementedResourceServiceServer) GetReviewSummary(context.Context, *GetReviewSummaryRequest) (*GetReviewSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReviewSummary not implemented")
}
func (UnimplementedResourceServiceServer) GetSecretSummary(context.Context, *GetSecretSummaryRequest) (*GetSecretSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecretSummary not implemented")
}
func (UnimplementedResourceServiceServer) GetIntegrationSummary(context.Context, *GetIntegrationSummaryRequest) (*GetIntegrationSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegrationSummary not implemented")
}
func (UnimplementedResourceServiceServer) GetIntegrationIdentitySummary(context.Context, *GetIntegrationIdentitySummaryRequest) (*GetIntegrationIdentitySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegrationIdentitySummary not implemented")
}
func (UnimplementedResourceServiceServer) GetIntegrationBindingSummary(context.Context, *GetIntegrationBindingSummaryRequest) (*GetIntegrationBindingSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntegrationBindingSummary not implemented")
}
func (UnimplementedResourceServiceServer) ListPolicy(context.Context, *ListPolicyOptions) (*accessv1.PolicyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPolicy not implemented")
}
func (UnimplementedResourceServiceServer) ListCatalog(context.Context, *ListCatalogOptions) (*accessv1.CatalogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCatalog not implemented")
}
func (UnimplementedResourceServiceServer) ListRequest(context.Context, *ListRequestOptions) (*accessv1.RequestList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRequest not implemented")
}
func (UnimplementedResourceServiceServer) ListReview(context.Context, *ListReviewOptions) (*accessv1.ReviewList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReview not implemented")
}
func (UnimplementedResourceServiceServer) ListSecret(context.Context, *ListSecretOptions) (*accessv1.SecretList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSecret not implemented")
}
func (UnimplementedResourceServiceServer) ListIntegration(context.Context, *ListIntegrationOptions) (*accessv1.IntegrationList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIntegration not implemented")
}
func (UnimplementedResourceServiceServer) ListIntegrationIdentity(context.Context, *ListIntegrationIdentityOptions) (*accessv1.IntegrationIdentityList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIntegrationIdentity not implemented")
}
func (UnimplementedResourceServiceServer) ListIntegrationBinding(context.Context, *ListIntegrationBindingOptions) (*accessv1.IntegrationBindingList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIntegrationBinding not implemented")
}
func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {}
func (UnimplementedResourceServiceServer) testEmbeddedByValue()                         {}

// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourceServiceServer will
// result in compilation errors.
type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	// If the following call pancis, it indicates UnimplementedResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ResourceService_ServiceDesc, srv)
}

func _ResourceService_GetPolicySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetPolicySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetPolicySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetPolicySummary(ctx, req.(*GetPolicySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetCatalogSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCatalogSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetCatalogSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetCatalogSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetCatalogSummary(ctx, req.(*GetCatalogSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetRequestSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequestSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetRequestSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetRequestSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetRequestSummary(ctx, req.(*GetRequestSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetReviewSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReviewSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetReviewSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetReviewSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetReviewSummary(ctx, req.(*GetReviewSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetSecretSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetSecretSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetSecretSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetSecretSummary(ctx, req.(*GetSecretSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetIntegrationSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrationSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetIntegrationSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetIntegrationSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetIntegrationSummary(ctx, req.(*GetIntegrationSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetIntegrationIdentitySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrationIdentitySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetIntegrationIdentitySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetIntegrationIdentitySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetIntegrationIdentitySummary(ctx, req.(*GetIntegrationIdentitySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_GetIntegrationBindingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrationBindingSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetIntegrationBindingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_GetIntegrationBindingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetIntegrationBindingSummary(ctx, req.(*GetIntegrationBindingSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPolicyOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListPolicy(ctx, req.(*ListPolicyOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatalogOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListCatalog(ctx, req.(*ListCatalogOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequestOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListRequest(ctx, req.(*ListRequestOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListReview(ctx, req.(*ListReviewOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSecretOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListSecret(ctx, req.(*ListSecretOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListIntegration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntegrationOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListIntegration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListIntegration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListIntegration(ctx, req.(*ListIntegrationOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListIntegrationIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntegrationIdentityOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListIntegrationIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListIntegrationIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListIntegrationIdentity(ctx, req.(*ListIntegrationIdentityOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_ListIntegrationBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntegrationBindingOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).ListIntegrationBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ResourceService_ListIntegrationBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).ListIntegrationBinding(ctx, req.(*ListIntegrationBindingOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.main.visibility.access.v1.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPolicySummary",
			Handler:    _ResourceService_GetPolicySummary_Handler,
		},
		{
			MethodName: "GetCatalogSummary",
			Handler:    _ResourceService_GetCatalogSummary_Handler,
		},
		{
			MethodName: "GetRequestSummary",
			Handler:    _ResourceService_GetRequestSummary_Handler,
		},
		{
			MethodName: "GetReviewSummary",
			Handler:    _ResourceService_GetReviewSummary_Handler,
		},
		{
			MethodName: "GetSecretSummary",
			Handler:    _ResourceService_GetSecretSummary_Handler,
		},
		{
			MethodName: "GetIntegrationSummary",
			Handler:    _ResourceService_GetIntegrationSummary_Handler,
		},
		{
			MethodName: "GetIntegrationIdentitySummary",
			Handler:    _ResourceService_GetIntegrationIdentitySummary_Handler,
		},
		{
			MethodName: "GetIntegrationBindingSummary",
			Handler:    _ResourceService_GetIntegrationBindingSummary_Handler,
		},
		{
			MethodName: "ListPolicy",
			Handler:    _ResourceService_ListPolicy_Handler,
		},
		{
			MethodName: "ListCatalog",
			Handler:    _ResourceService_ListCatalog_Handler,
		},
		{
			MethodName: "ListRequest",
			Handler:    _ResourceService_ListRequest_Handler,
		},
		{
			MethodName: "ListReview",
			Handler:    _ResourceService_ListReview_Handler,
		},
		{
			MethodName: "ListSecret",
			Handler:    _ResourceService_ListSecret_Handler,
		},
		{
			MethodName: "ListIntegration",
			Handler:    _ResourceService_ListIntegration_Handler,
		},
		{
			MethodName: "ListIntegrationIdentity",
			Handler:    _ResourceService_ListIntegrationIdentity_Handler,
		},
		{
			MethodName: "ListIntegrationBinding",
			Handler:    _ResourceService_ListIntegrationBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vaccessv1.proto",
}
