// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "apis/protobuf/main/visibilityv1/metrics/vmetricsv1.proto" (package "octelium.api.main.visibility.metrics.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MetricsService } from "./vmetricsv1";
import type { ListMetricCatalogResponse } from "./vmetricsv1";
import type { ListMetricCatalogRequest } from "./vmetricsv1";
import type { ListMetricDescriptorsResponse } from "./vmetricsv1";
import type { ListMetricDescriptorsRequest } from "./vmetricsv1";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { QueryMetricsResponse } from "./vmetricsv1";
import type { QueryMetricsRequest } from "./vmetricsv1";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service octelium.api.main.visibility.metrics.v1.MetricsService
 */
export interface IMetricsServiceClient {
    /**
     * @generated from protobuf rpc: QueryMetrics
     */
    queryMetrics(input: QueryMetricsRequest, options?: RpcOptions): UnaryCall<QueryMetricsRequest, QueryMetricsResponse>;
    /**
     * @generated from protobuf rpc: ListMetricDescriptors
     */
    listMetricDescriptors(input: ListMetricDescriptorsRequest, options?: RpcOptions): UnaryCall<ListMetricDescriptorsRequest, ListMetricDescriptorsResponse>;
    /**
     * @generated from protobuf rpc: ListMetricCatalog
     */
    listMetricCatalog(input: ListMetricCatalogRequest, options?: RpcOptions): UnaryCall<ListMetricCatalogRequest, ListMetricCatalogResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.visibility.metrics.v1.MetricsService
 */
export class MetricsServiceClient implements IMetricsServiceClient, ServiceInfo {
    typeName = MetricsService.typeName;
    methods = MetricsService.methods;
    options = MetricsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: QueryMetrics
     */
    queryMetrics(input: QueryMetricsRequest, options?: RpcOptions): UnaryCall<QueryMetricsRequest, QueryMetricsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<QueryMetricsRequest, QueryMetricsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMetricDescriptors
     */
    listMetricDescriptors(input: ListMetricDescriptorsRequest, options?: RpcOptions): UnaryCall<ListMetricDescriptorsRequest, ListMetricDescriptorsResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMetricDescriptorsRequest, ListMetricDescriptorsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListMetricCatalog
     */
    listMetricCatalog(input: ListMetricCatalogRequest, options?: RpcOptions): UnaryCall<ListMetricCatalogRequest, ListMetricCatalogResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMetricCatalogRequest, ListMetricCatalogResponse>("unary", this._transport, method, opt, input);
    }
}
