// Copyright (c) 2025-present Octelium Labs, LLC. All rights reserved.
//
// This software is licensed under the Octelium Enterprise Source-Available License.
// Commercial and production use is strictly prohibited without a valid
// Commercial Agreement from Octelium Labs, LLC.
//
// See the LICENSE file in the repository root for full license text.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: accessv1.proto

package accessv1

import (
	context "context"
	metav1 "github.com/octelium/octelium/apis/main/metav1"
	userv1 "github.com/octelium/octelium/apis/main/userv1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MainService_CreateCatalog_FullMethodName = "/octelium.api.main.access.v1.MainService/CreateCatalog"
	MainService_GetCatalog_FullMethodName    = "/octelium.api.main.access.v1.MainService/GetCatalog"
	MainService_UpdateCatalog_FullMethodName = "/octelium.api.main.access.v1.MainService/UpdateCatalog"
	MainService_DeleteCatalog_FullMethodName = "/octelium.api.main.access.v1.MainService/DeleteCatalog"
	MainService_ListCatalog_FullMethodName   = "/octelium.api.main.access.v1.MainService/ListCatalog"
	MainService_CreatePolicy_FullMethodName  = "/octelium.api.main.access.v1.MainService/CreatePolicy"
	MainService_GetPolicy_FullMethodName     = "/octelium.api.main.access.v1.MainService/GetPolicy"
	MainService_UpdatePolicy_FullMethodName  = "/octelium.api.main.access.v1.MainService/UpdatePolicy"
	MainService_DeletePolicy_FullMethodName  = "/octelium.api.main.access.v1.MainService/DeletePolicy"
	MainService_ListPolicy_FullMethodName    = "/octelium.api.main.access.v1.MainService/ListPolicy"
	MainService_UpdateRequest_FullMethodName = "/octelium.api.main.access.v1.MainService/UpdateRequest"
	MainService_GetRequest_FullMethodName    = "/octelium.api.main.access.v1.MainService/GetRequest"
	MainService_DeleteRequest_FullMethodName = "/octelium.api.main.access.v1.MainService/DeleteRequest"
	MainService_ListRequest_FullMethodName   = "/octelium.api.main.access.v1.MainService/ListRequest"
	MainService_ListReview_FullMethodName    = "/octelium.api.main.access.v1.MainService/ListReview"
	MainService_GetReview_FullMethodName     = "/octelium.api.main.access.v1.MainService/GetReview"
	MainService_UpdateReview_FullMethodName  = "/octelium.api.main.access.v1.MainService/UpdateReview"
	MainService_DeleteReview_FullMethodName  = "/octelium.api.main.access.v1.MainService/DeleteReview"
)

// MainServiceClient is the client API for MainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MainServiceClient interface {
	CreateCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*Catalog, error)
	GetCatalog(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Catalog, error)
	UpdateCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*Catalog, error)
	DeleteCatalog(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error)
	ListCatalog(ctx context.Context, in *ListCatalogOptions, opts ...grpc.CallOption) (*CatalogList, error)
	CreatePolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Policy, error)
	GetPolicy(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Policy, error)
	UpdatePolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Policy, error)
	DeletePolicy(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error)
	ListPolicy(ctx context.Context, in *ListPolicyOptions, opts ...grpc.CallOption) (*PolicyList, error)
	UpdateRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Request, error)
	GetRequest(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Request, error)
	DeleteRequest(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error)
	ListRequest(ctx context.Context, in *ListRequestOptions, opts ...grpc.CallOption) (*RequestList, error)
	ListReview(ctx context.Context, in *ListReviewOptions, opts ...grpc.CallOption) (*ReviewList, error)
	GetReview(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Review, error)
	UpdateReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error)
	DeleteReview(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error)
}

type mainServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMainServiceClient(cc grpc.ClientConnInterface) MainServiceClient {
	return &mainServiceClient{cc}
}

func (c *mainServiceClient) CreateCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*Catalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Catalog)
	err := c.cc.Invoke(ctx, MainService_CreateCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetCatalog(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Catalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Catalog)
	err := c.cc.Invoke(ctx, MainService_GetCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateCatalog(ctx context.Context, in *Catalog, opts ...grpc.CallOption) (*Catalog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Catalog)
	err := c.cc.Invoke(ctx, MainService_UpdateCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeleteCatalog(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, MainService_DeleteCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListCatalog(ctx context.Context, in *ListCatalogOptions, opts ...grpc.CallOption) (*CatalogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatalogList)
	err := c.cc.Invoke(ctx, MainService_ListCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) CreatePolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, MainService_CreatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetPolicy(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, MainService_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdatePolicy(ctx context.Context, in *Policy, opts ...grpc.CallOption) (*Policy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Policy)
	err := c.cc.Invoke(ctx, MainService_UpdatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeletePolicy(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, MainService_DeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListPolicy(ctx context.Context, in *ListPolicyOptions, opts ...grpc.CallOption) (*PolicyList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PolicyList)
	err := c.cc.Invoke(ctx, MainService_ListPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, MainService_UpdateRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetRequest(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, MainService_GetRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeleteRequest(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, MainService_DeleteRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListRequest(ctx context.Context, in *ListRequestOptions, opts ...grpc.CallOption) (*RequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestList)
	err := c.cc.Invoke(ctx, MainService_ListRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) ListReview(ctx context.Context, in *ListReviewOptions, opts ...grpc.CallOption) (*ReviewList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewList)
	err := c.cc.Invoke(ctx, MainService_ListReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) GetReview(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Review, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Review)
	err := c.cc.Invoke(ctx, MainService_GetReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) UpdateReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Review)
	err := c.cc.Invoke(ctx, MainService_UpdateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mainServiceClient) DeleteReview(ctx context.Context, in *metav1.DeleteOptions, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, MainService_DeleteReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MainServiceServer is the server API for MainService service.
// All implementations must embed UnimplementedMainServiceServer
// for forward compatibility.
type MainServiceServer interface {
	CreateCatalog(context.Context, *Catalog) (*Catalog, error)
	GetCatalog(context.Context, *metav1.GetOptions) (*Catalog, error)
	UpdateCatalog(context.Context, *Catalog) (*Catalog, error)
	DeleteCatalog(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error)
	ListCatalog(context.Context, *ListCatalogOptions) (*CatalogList, error)
	CreatePolicy(context.Context, *Policy) (*Policy, error)
	GetPolicy(context.Context, *metav1.GetOptions) (*Policy, error)
	UpdatePolicy(context.Context, *Policy) (*Policy, error)
	DeletePolicy(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error)
	ListPolicy(context.Context, *ListPolicyOptions) (*PolicyList, error)
	UpdateRequest(context.Context, *Request) (*Request, error)
	GetRequest(context.Context, *metav1.GetOptions) (*Request, error)
	DeleteRequest(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error)
	ListRequest(context.Context, *ListRequestOptions) (*RequestList, error)
	ListReview(context.Context, *ListReviewOptions) (*ReviewList, error)
	GetReview(context.Context, *metav1.GetOptions) (*Review, error)
	UpdateReview(context.Context, *Review) (*Review, error)
	DeleteReview(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error)
	mustEmbedUnimplementedMainServiceServer()
}

// UnimplementedMainServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMainServiceServer struct{}

func (UnimplementedMainServiceServer) CreateCatalog(context.Context, *Catalog) (*Catalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCatalog not implemented")
}
func (UnimplementedMainServiceServer) GetCatalog(context.Context, *metav1.GetOptions) (*Catalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatalog not implemented")
}
func (UnimplementedMainServiceServer) UpdateCatalog(context.Context, *Catalog) (*Catalog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCatalog not implemented")
}
func (UnimplementedMainServiceServer) DeleteCatalog(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCatalog not implemented")
}
func (UnimplementedMainServiceServer) ListCatalog(context.Context, *ListCatalogOptions) (*CatalogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCatalog not implemented")
}
func (UnimplementedMainServiceServer) CreatePolicy(context.Context, *Policy) (*Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePolicy not implemented")
}
func (UnimplementedMainServiceServer) GetPolicy(context.Context, *metav1.GetOptions) (*Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedMainServiceServer) UpdatePolicy(context.Context, *Policy) (*Policy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePolicy not implemented")
}
func (UnimplementedMainServiceServer) DeletePolicy(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedMainServiceServer) ListPolicy(context.Context, *ListPolicyOptions) (*PolicyList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPolicy not implemented")
}
func (UnimplementedMainServiceServer) UpdateRequest(context.Context, *Request) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRequest not implemented")
}
func (UnimplementedMainServiceServer) GetRequest(context.Context, *metav1.GetOptions) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedMainServiceServer) DeleteRequest(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRequest not implemented")
}
func (UnimplementedMainServiceServer) ListRequest(context.Context, *ListRequestOptions) (*RequestList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRequest not implemented")
}
func (UnimplementedMainServiceServer) ListReview(context.Context, *ListReviewOptions) (*ReviewList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReview not implemented")
}
func (UnimplementedMainServiceServer) GetReview(context.Context, *metav1.GetOptions) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReview not implemented")
}
func (UnimplementedMainServiceServer) UpdateReview(context.Context, *Review) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReview not implemented")
}
func (UnimplementedMainServiceServer) DeleteReview(context.Context, *metav1.DeleteOptions) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReview not implemented")
}
func (UnimplementedMainServiceServer) mustEmbedUnimplementedMainServiceServer() {}
func (UnimplementedMainServiceServer) testEmbeddedByValue()                     {}

// UnsafeMainServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MainServiceServer will
// result in compilation errors.
type UnsafeMainServiceServer interface {
	mustEmbedUnimplementedMainServiceServer()
}

func RegisterMainServiceServer(s grpc.ServiceRegistrar, srv MainServiceServer) {
	// If the following call pancis, it indicates UnimplementedMainServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MainService_ServiceDesc, srv)
}

func _MainService_CreateCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Catalog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).CreateCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_CreateCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).CreateCatalog(ctx, req.(*Catalog))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetCatalog(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Catalog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateCatalog(ctx, req.(*Catalog))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeleteCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeleteCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeleteCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeleteCatalog(ctx, req.(*metav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCatalogOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListCatalog(ctx, req.(*ListCatalogOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_CreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).CreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_CreatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).CreatePolicy(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetPolicy(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Policy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdatePolicy(ctx, req.(*Policy))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeletePolicy(ctx, req.(*metav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPolicyOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListPolicy(ctx, req.(*ListPolicyOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetRequest(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeleteRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeleteRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeleteRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeleteRequest(ctx, req.(*metav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequestOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListRequest(ctx, req.(*ListRequestOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_ListReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).ListReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_ListReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).ListReview(ctx, req.(*ListReviewOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_GetReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).GetReview(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_UpdateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Review)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).UpdateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_UpdateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).UpdateReview(ctx, req.(*Review))
	}
	return interceptor(ctx, in, info, handler)
}

func _MainService_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.DeleteOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServiceServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MainService_DeleteReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServiceServer).DeleteReview(ctx, req.(*metav1.DeleteOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// MainService_ServiceDesc is the grpc.ServiceDesc for MainService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MainService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.main.access.v1.MainService",
	HandlerType: (*MainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCatalog",
			Handler:    _MainService_CreateCatalog_Handler,
		},
		{
			MethodName: "GetCatalog",
			Handler:    _MainService_GetCatalog_Handler,
		},
		{
			MethodName: "UpdateCatalog",
			Handler:    _MainService_UpdateCatalog_Handler,
		},
		{
			MethodName: "DeleteCatalog",
			Handler:    _MainService_DeleteCatalog_Handler,
		},
		{
			MethodName: "ListCatalog",
			Handler:    _MainService_ListCatalog_Handler,
		},
		{
			MethodName: "CreatePolicy",
			Handler:    _MainService_CreatePolicy_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _MainService_GetPolicy_Handler,
		},
		{
			MethodName: "UpdatePolicy",
			Handler:    _MainService_UpdatePolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _MainService_DeletePolicy_Handler,
		},
		{
			MethodName: "ListPolicy",
			Handler:    _MainService_ListPolicy_Handler,
		},
		{
			MethodName: "UpdateRequest",
			Handler:    _MainService_UpdateRequest_Handler,
		},
		{
			MethodName: "GetRequest",
			Handler:    _MainService_GetRequest_Handler,
		},
		{
			MethodName: "DeleteRequest",
			Handler:    _MainService_DeleteRequest_Handler,
		},
		{
			MethodName: "ListRequest",
			Handler:    _MainService_ListRequest_Handler,
		},
		{
			MethodName: "ListReview",
			Handler:    _MainService_ListReview_Handler,
		},
		{
			MethodName: "GetReview",
			Handler:    _MainService_GetReview_Handler,
		},
		{
			MethodName: "UpdateReview",
			Handler:    _MainService_UpdateReview_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _MainService_DeleteReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accessv1.proto",
}

const (
	UserService_CreateRequest_FullMethodName      = "/octelium.api.main.access.v1.UserService/CreateRequest"
	UserService_UpdateRequest_FullMethodName      = "/octelium.api.main.access.v1.UserService/UpdateRequest"
	UserService_GetRequest_FullMethodName         = "/octelium.api.main.access.v1.UserService/GetRequest"
	UserService_CancelRequest_FullMethodName      = "/octelium.api.main.access.v1.UserService/CancelRequest"
	UserService_ListRequest_FullMethodName        = "/octelium.api.main.access.v1.UserService/ListRequest"
	UserService_ListCatalog_FullMethodName        = "/octelium.api.main.access.v1.UserService/ListCatalog"
	UserService_ListCatalogService_FullMethodName = "/octelium.api.main.access.v1.UserService/ListCatalogService"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Request, error)
	UpdateRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Request, error)
	GetRequest(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Request, error)
	CancelRequest(ctx context.Context, in *CancelRequestRequest, opts ...grpc.CallOption) (*metav1.OperationResult, error)
	ListRequest(ctx context.Context, in *ListUserRequestOptions, opts ...grpc.CallOption) (*RequestList, error)
	ListCatalog(ctx context.Context, in *ListUserCatalogOptions, opts ...grpc.CallOption) (*CatalogList, error)
	ListCatalogService(ctx context.Context, in *ListUserCatalogServiceOptions, opts ...grpc.CallOption) (*userv1.ServiceList, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, UserService_CreateRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, UserService_UpdateRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetRequest(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, UserService_GetRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CancelRequest(ctx context.Context, in *CancelRequestRequest, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, UserService_CancelRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListRequest(ctx context.Context, in *ListUserRequestOptions, opts ...grpc.CallOption) (*RequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestList)
	err := c.cc.Invoke(ctx, UserService_ListRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListCatalog(ctx context.Context, in *ListUserCatalogOptions, opts ...grpc.CallOption) (*CatalogList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CatalogList)
	err := c.cc.Invoke(ctx, UserService_ListCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListCatalogService(ctx context.Context, in *ListUserCatalogServiceOptions, opts ...grpc.CallOption) (*userv1.ServiceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(userv1.ServiceList)
	err := c.cc.Invoke(ctx, UserService_ListCatalogService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	CreateRequest(context.Context, *Request) (*Request, error)
	UpdateRequest(context.Context, *Request) (*Request, error)
	GetRequest(context.Context, *metav1.GetOptions) (*Request, error)
	CancelRequest(context.Context, *CancelRequestRequest) (*metav1.OperationResult, error)
	ListRequest(context.Context, *ListUserRequestOptions) (*RequestList, error)
	ListCatalog(context.Context, *ListUserCatalogOptions) (*CatalogList, error)
	ListCatalogService(context.Context, *ListUserCatalogServiceOptions) (*userv1.ServiceList, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) CreateRequest(context.Context, *Request) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRequest not implemented")
}
func (UnimplementedUserServiceServer) UpdateRequest(context.Context, *Request) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRequest not implemented")
}
func (UnimplementedUserServiceServer) GetRequest(context.Context, *metav1.GetOptions) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedUserServiceServer) CancelRequest(context.Context, *CancelRequestRequest) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRequest not implemented")
}
func (UnimplementedUserServiceServer) ListRequest(context.Context, *ListUserRequestOptions) (*RequestList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRequest not implemented")
}
func (UnimplementedUserServiceServer) ListCatalog(context.Context, *ListUserCatalogOptions) (*CatalogList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCatalog not implemented")
}
func (UnimplementedUserServiceServer) ListCatalogService(context.Context, *ListUserCatalogServiceOptions) (*userv1.ServiceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCatalogService not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_CreateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CreateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetRequest(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CancelRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CancelRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_CancelRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CancelRequest(ctx, req.(*CancelRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequestOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListRequest(ctx, req.(*ListUserRequestOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCatalogOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListCatalog(ctx, req.(*ListUserCatalogOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListCatalogService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCatalogServiceOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListCatalogService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ListCatalogService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListCatalogService(ctx, req.(*ListUserCatalogServiceOptions))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.main.access.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRequest",
			Handler:    _UserService_CreateRequest_Handler,
		},
		{
			MethodName: "UpdateRequest",
			Handler:    _UserService_UpdateRequest_Handler,
		},
		{
			MethodName: "GetRequest",
			Handler:    _UserService_GetRequest_Handler,
		},
		{
			MethodName: "CancelRequest",
			Handler:    _UserService_CancelRequest_Handler,
		},
		{
			MethodName: "ListRequest",
			Handler:    _UserService_ListRequest_Handler,
		},
		{
			MethodName: "ListCatalog",
			Handler:    _UserService_ListCatalog_Handler,
		},
		{
			MethodName: "ListCatalogService",
			Handler:    _UserService_ListCatalogService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accessv1.proto",
}

const (
	ReviewerService_GetRequest_FullMethodName   = "/octelium.api.main.access.v1.ReviewerService/GetRequest"
	ReviewerService_ListRequest_FullMethodName  = "/octelium.api.main.access.v1.ReviewerService/ListRequest"
	ReviewerService_ListReview_FullMethodName   = "/octelium.api.main.access.v1.ReviewerService/ListReview"
	ReviewerService_GetReview_FullMethodName    = "/octelium.api.main.access.v1.ReviewerService/GetReview"
	ReviewerService_CreateReview_FullMethodName = "/octelium.api.main.access.v1.ReviewerService/CreateReview"
	ReviewerService_UpdateReview_FullMethodName = "/octelium.api.main.access.v1.ReviewerService/UpdateReview"
	ReviewerService_CancelReview_FullMethodName = "/octelium.api.main.access.v1.ReviewerService/CancelReview"
)

// ReviewerServiceClient is the client API for ReviewerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewerServiceClient interface {
	GetRequest(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Request, error)
	ListRequest(ctx context.Context, in *ListReviewerRequestOptions, opts ...grpc.CallOption) (*RequestList, error)
	ListReview(ctx context.Context, in *ListReviewerReviewOptions, opts ...grpc.CallOption) (*ReviewList, error)
	GetReview(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Review, error)
	CreateReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error)
	UpdateReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error)
	CancelReview(ctx context.Context, in *CancelReviewRequest, opts ...grpc.CallOption) (*metav1.OperationResult, error)
}

type reviewerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewerServiceClient(cc grpc.ClientConnInterface) ReviewerServiceClient {
	return &reviewerServiceClient{cc}
}

func (c *reviewerServiceClient) GetRequest(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Request, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Request)
	err := c.cc.Invoke(ctx, ReviewerService_GetRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewerServiceClient) ListRequest(ctx context.Context, in *ListReviewerRequestOptions, opts ...grpc.CallOption) (*RequestList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestList)
	err := c.cc.Invoke(ctx, ReviewerService_ListRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewerServiceClient) ListReview(ctx context.Context, in *ListReviewerReviewOptions, opts ...grpc.CallOption) (*ReviewList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewList)
	err := c.cc.Invoke(ctx, ReviewerService_ListReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewerServiceClient) GetReview(ctx context.Context, in *metav1.GetOptions, opts ...grpc.CallOption) (*Review, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Review)
	err := c.cc.Invoke(ctx, ReviewerService_GetReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewerServiceClient) CreateReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Review)
	err := c.cc.Invoke(ctx, ReviewerService_CreateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewerServiceClient) UpdateReview(ctx context.Context, in *Review, opts ...grpc.CallOption) (*Review, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Review)
	err := c.cc.Invoke(ctx, ReviewerService_UpdateReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewerServiceClient) CancelReview(ctx context.Context, in *CancelReviewRequest, opts ...grpc.CallOption) (*metav1.OperationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(metav1.OperationResult)
	err := c.cc.Invoke(ctx, ReviewerService_CancelReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewerServiceServer is the server API for ReviewerService service.
// All implementations must embed UnimplementedReviewerServiceServer
// for forward compatibility.
type ReviewerServiceServer interface {
	GetRequest(context.Context, *metav1.GetOptions) (*Request, error)
	ListRequest(context.Context, *ListReviewerRequestOptions) (*RequestList, error)
	ListReview(context.Context, *ListReviewerReviewOptions) (*ReviewList, error)
	GetReview(context.Context, *metav1.GetOptions) (*Review, error)
	CreateReview(context.Context, *Review) (*Review, error)
	UpdateReview(context.Context, *Review) (*Review, error)
	CancelReview(context.Context, *CancelReviewRequest) (*metav1.OperationResult, error)
	mustEmbedUnimplementedReviewerServiceServer()
}

// UnimplementedReviewerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewerServiceServer struct{}

func (UnimplementedReviewerServiceServer) GetRequest(context.Context, *metav1.GetOptions) (*Request, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedReviewerServiceServer) ListRequest(context.Context, *ListReviewerRequestOptions) (*RequestList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRequest not implemented")
}
func (UnimplementedReviewerServiceServer) ListReview(context.Context, *ListReviewerReviewOptions) (*ReviewList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReview not implemented")
}
func (UnimplementedReviewerServiceServer) GetReview(context.Context, *metav1.GetOptions) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReview not implemented")
}
func (UnimplementedReviewerServiceServer) CreateReview(context.Context, *Review) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReview not implemented")
}
func (UnimplementedReviewerServiceServer) UpdateReview(context.Context, *Review) (*Review, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateReview not implemented")
}
func (UnimplementedReviewerServiceServer) CancelReview(context.Context, *CancelReviewRequest) (*metav1.OperationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelReview not implemented")
}
func (UnimplementedReviewerServiceServer) mustEmbedUnimplementedReviewerServiceServer() {}
func (UnimplementedReviewerServiceServer) testEmbeddedByValue()                         {}

// UnsafeReviewerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewerServiceServer will
// result in compilation errors.
type UnsafeReviewerServiceServer interface {
	mustEmbedUnimplementedReviewerServiceServer()
}

func RegisterReviewerServiceServer(s grpc.ServiceRegistrar, srv ReviewerServiceServer) {
	// If the following call pancis, it indicates UnimplementedReviewerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReviewerService_ServiceDesc, srv)
}

func _ReviewerService_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewerServiceServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewerService_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewerServiceServer).GetRequest(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewerService_ListRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewerRequestOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewerServiceServer).ListRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewerService_ListRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewerServiceServer).ListRequest(ctx, req.(*ListReviewerRequestOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewerService_ListReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReviewerReviewOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewerServiceServer).ListReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewerService_ListReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewerServiceServer).ListReview(ctx, req.(*ListReviewerReviewOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewerService_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metav1.GetOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewerServiceServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewerService_GetReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewerServiceServer).GetReview(ctx, req.(*metav1.GetOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewerService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Review)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewerServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewerService_CreateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewerServiceServer).CreateReview(ctx, req.(*Review))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewerService_UpdateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Review)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewerServiceServer).UpdateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewerService_UpdateReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewerServiceServer).UpdateReview(ctx, req.(*Review))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewerService_CancelReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewerServiceServer).CancelReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReviewerService_CancelReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewerServiceServer).CancelReview(ctx, req.(*CancelReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReviewerService_ServiceDesc is the grpc.ServiceDesc for ReviewerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "octelium.api.main.access.v1.ReviewerService",
	HandlerType: (*ReviewerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRequest",
			Handler:    _ReviewerService_GetRequest_Handler,
		},
		{
			MethodName: "ListRequest",
			Handler:    _ReviewerService_ListRequest_Handler,
		},
		{
			MethodName: "ListReview",
			Handler:    _ReviewerService_ListReview_Handler,
		},
		{
			MethodName: "GetReview",
			Handler:    _ReviewerService_GetReview_Handler,
		},
		{
			MethodName: "CreateReview",
			Handler:    _ReviewerService_CreateReview_Handler,
		},
		{
			MethodName: "UpdateReview",
			Handler:    _ReviewerService_UpdateReview_Handler,
		},
		{
			MethodName: "CancelReview",
			Handler:    _ReviewerService_CancelReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accessv1.proto",
}
