// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "apis/protobuf/main/accessv1/accessv1.proto" (package "octelium.api.main.access.v1", syntax proto3)
// tslint:disable
//
//
// Copyright (c) 2020-present Octelium. All rights reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3,
// as published by the Free Software Foundation of the License.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
import { ReviewerService } from "./accessv1";
import type { CancelReviewRequest } from "./accessv1";
import type { ListReviewerReviewOptions } from "./accessv1";
import type { ListReviewerRequestOptions } from "./accessv1";
import { UserService } from "./accessv1";
import type { SubjectUser } from "./accessv1";
import type { GetSubjectUserRequest } from "./accessv1";
import type { SubjectUserList } from "./accessv1";
import type { ListSubjectUserOptions } from "./accessv1";
import type { ServiceList } from "../userv1/userv1";
import type { ListUserCatalogServiceOptions } from "./accessv1";
import type { ListUserCatalogOptions } from "./accessv1";
import type { ListUserRequestOptions } from "./accessv1";
import type { CancelRequestRequest } from "./accessv1";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MainService } from "./accessv1";
import type { Review } from "./accessv1";
import type { ReviewList } from "./accessv1";
import type { ListReviewOptions } from "./accessv1";
import type { RevokeRequestRequest } from "./accessv1";
import type { RequestList } from "./accessv1";
import type { ListRequestOptions } from "./accessv1";
import type { Request } from "./accessv1";
import type { PolicyList } from "./accessv1";
import type { ListPolicyOptions } from "./accessv1";
import type { Policy } from "./accessv1";
import type { CatalogList } from "./accessv1";
import type { ListCatalogOptions } from "./accessv1";
import type { OperationResult } from "../metav1/metav1";
import type { DeleteOptions } from "../metav1/metav1";
import type { GetOptions } from "../metav1/metav1";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Catalog } from "./accessv1";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service octelium.api.main.access.v1.MainService
 */
export interface IMainServiceClient {
    /**
     * @generated from protobuf rpc: CreateCatalog
     */
    createCatalog(input: Catalog, options?: RpcOptions): UnaryCall<Catalog, Catalog>;
    /**
     * @generated from protobuf rpc: GetCatalog
     */
    getCatalog(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Catalog>;
    /**
     * @generated from protobuf rpc: UpdateCatalog
     */
    updateCatalog(input: Catalog, options?: RpcOptions): UnaryCall<Catalog, Catalog>;
    /**
     * @generated from protobuf rpc: DeleteCatalog
     */
    deleteCatalog(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * @generated from protobuf rpc: ListCatalog
     */
    listCatalog(input: ListCatalogOptions, options?: RpcOptions): UnaryCall<ListCatalogOptions, CatalogList>;
    /**
     * @generated from protobuf rpc: CreatePolicy
     */
    createPolicy(input: Policy, options?: RpcOptions): UnaryCall<Policy, Policy>;
    /**
     * @generated from protobuf rpc: GetPolicy
     */
    getPolicy(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Policy>;
    /**
     * @generated from protobuf rpc: UpdatePolicy
     */
    updatePolicy(input: Policy, options?: RpcOptions): UnaryCall<Policy, Policy>;
    /**
     * @generated from protobuf rpc: DeletePolicy
     */
    deletePolicy(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * @generated from protobuf rpc: ListPolicy
     */
    listPolicy(input: ListPolicyOptions, options?: RpcOptions): UnaryCall<ListPolicyOptions, PolicyList>;
    /**
     * @generated from protobuf rpc: GetRequest
     */
    getRequest(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Request>;
    /**
     * @generated from protobuf rpc: DeleteRequest
     */
    deleteRequest(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * @generated from protobuf rpc: ListRequest
     */
    listRequest(input: ListRequestOptions, options?: RpcOptions): UnaryCall<ListRequestOptions, RequestList>;
    /**
     * @generated from protobuf rpc: RevokeRequest
     */
    revokeRequest(input: RevokeRequestRequest, options?: RpcOptions): UnaryCall<RevokeRequestRequest, OperationResult>;
    /**
     * @generated from protobuf rpc: ListReview
     */
    listReview(input: ListReviewOptions, options?: RpcOptions): UnaryCall<ListReviewOptions, ReviewList>;
    /**
     * @generated from protobuf rpc: GetReview
     */
    getReview(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Review>;
    /**
     * @generated from protobuf rpc: DeleteReview
     */
    deleteReview(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
}
/**
 * @generated from protobuf service octelium.api.main.access.v1.MainService
 */
export class MainServiceClient implements IMainServiceClient, ServiceInfo {
    typeName = MainService.typeName;
    methods = MainService.methods;
    options = MainService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateCatalog
     */
    createCatalog(input: Catalog, options?: RpcOptions): UnaryCall<Catalog, Catalog> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Catalog, Catalog>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCatalog
     */
    getCatalog(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Catalog> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Catalog>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateCatalog
     */
    updateCatalog(input: Catalog, options?: RpcOptions): UnaryCall<Catalog, Catalog> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Catalog, Catalog>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteCatalog
     */
    deleteCatalog(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCatalog
     */
    listCatalog(input: ListCatalogOptions, options?: RpcOptions): UnaryCall<ListCatalogOptions, CatalogList> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCatalogOptions, CatalogList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreatePolicy
     */
    createPolicy(input: Policy, options?: RpcOptions): UnaryCall<Policy, Policy> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<Policy, Policy>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPolicy
     */
    getPolicy(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Policy> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Policy>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdatePolicy
     */
    updatePolicy(input: Policy, options?: RpcOptions): UnaryCall<Policy, Policy> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<Policy, Policy>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeletePolicy
     */
    deletePolicy(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListPolicy
     */
    listPolicy(input: ListPolicyOptions, options?: RpcOptions): UnaryCall<ListPolicyOptions, PolicyList> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListPolicyOptions, PolicyList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRequest
     */
    getRequest(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Request> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Request>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteRequest
     */
    deleteRequest(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListRequest
     */
    listRequest(input: ListRequestOptions, options?: RpcOptions): UnaryCall<ListRequestOptions, RequestList> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRequestOptions, RequestList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RevokeRequest
     */
    revokeRequest(input: RevokeRequestRequest, options?: RpcOptions): UnaryCall<RevokeRequestRequest, OperationResult> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevokeRequestRequest, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListReview
     */
    listReview(input: ListReviewOptions, options?: RpcOptions): UnaryCall<ListReviewOptions, ReviewList> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListReviewOptions, ReviewList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetReview
     */
    getReview(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Review> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Review>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteReview
     */
    deleteReview(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service octelium.api.main.access.v1.UserService
 */
export interface IUserServiceClient {
    /**
     * @generated from protobuf rpc: CreateRequest
     */
    createRequest(input: Request, options?: RpcOptions): UnaryCall<Request, Request>;
    /**
     * @generated from protobuf rpc: CreateRequestForSubject
     */
    createRequestForSubject(input: Request, options?: RpcOptions): UnaryCall<Request, Request>;
    /**
     * @generated from protobuf rpc: UpdateRequest
     */
    updateRequest(input: Request, options?: RpcOptions): UnaryCall<Request, Request>;
    /**
     * @generated from protobuf rpc: GetRequest
     */
    getRequest(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Request>;
    /**
     * @generated from protobuf rpc: CancelRequest
     */
    cancelRequest(input: CancelRequestRequest, options?: RpcOptions): UnaryCall<CancelRequestRequest, OperationResult>;
    /**
     * @generated from protobuf rpc: ListRequest
     */
    listRequest(input: ListUserRequestOptions, options?: RpcOptions): UnaryCall<ListUserRequestOptions, RequestList>;
    /**
     * @generated from protobuf rpc: ListCatalog
     */
    listCatalog(input: ListUserCatalogOptions, options?: RpcOptions): UnaryCall<ListUserCatalogOptions, CatalogList>;
    /**
     * @generated from protobuf rpc: ListCatalogService
     */
    listCatalogService(input: ListUserCatalogServiceOptions, options?: RpcOptions): UnaryCall<ListUserCatalogServiceOptions, ServiceList>;
    /**
     * @generated from protobuf rpc: ListSubjectUser
     */
    listSubjectUser(input: ListSubjectUserOptions, options?: RpcOptions): UnaryCall<ListSubjectUserOptions, SubjectUserList>;
    /**
     * @generated from protobuf rpc: GetSubjectUser
     */
    getSubjectUser(input: GetSubjectUserRequest, options?: RpcOptions): UnaryCall<GetSubjectUserRequest, SubjectUser>;
}
/**
 * @generated from protobuf service octelium.api.main.access.v1.UserService
 */
export class UserServiceClient implements IUserServiceClient, ServiceInfo {
    typeName = UserService.typeName;
    methods = UserService.methods;
    options = UserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateRequest
     */
    createRequest(input: Request, options?: RpcOptions): UnaryCall<Request, Request> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Request, Request>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateRequestForSubject
     */
    createRequestForSubject(input: Request, options?: RpcOptions): UnaryCall<Request, Request> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Request, Request>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateRequest
     */
    updateRequest(input: Request, options?: RpcOptions): UnaryCall<Request, Request> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<Request, Request>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRequest
     */
    getRequest(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Request> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Request>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelRequest
     */
    cancelRequest(input: CancelRequestRequest, options?: RpcOptions): UnaryCall<CancelRequestRequest, OperationResult> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelRequestRequest, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListRequest
     */
    listRequest(input: ListUserRequestOptions, options?: RpcOptions): UnaryCall<ListUserRequestOptions, RequestList> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListUserRequestOptions, RequestList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCatalog
     */
    listCatalog(input: ListUserCatalogOptions, options?: RpcOptions): UnaryCall<ListUserCatalogOptions, CatalogList> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListUserCatalogOptions, CatalogList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCatalogService
     */
    listCatalogService(input: ListUserCatalogServiceOptions, options?: RpcOptions): UnaryCall<ListUserCatalogServiceOptions, ServiceList> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListUserCatalogServiceOptions, ServiceList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSubjectUser
     */
    listSubjectUser(input: ListSubjectUserOptions, options?: RpcOptions): UnaryCall<ListSubjectUserOptions, SubjectUserList> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSubjectUserOptions, SubjectUserList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSubjectUser
     */
    getSubjectUser(input: GetSubjectUserRequest, options?: RpcOptions): UnaryCall<GetSubjectUserRequest, SubjectUser> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSubjectUserRequest, SubjectUser>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service octelium.api.main.access.v1.ReviewerService
 */
export interface IReviewerServiceClient {
    /**
     * @generated from protobuf rpc: GetRequest
     */
    getRequest(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Request>;
    /**
     * @generated from protobuf rpc: ListRequest
     */
    listRequest(input: ListReviewerRequestOptions, options?: RpcOptions): UnaryCall<ListReviewerRequestOptions, RequestList>;
    /**
     * @generated from protobuf rpc: ListReview
     */
    listReview(input: ListReviewerReviewOptions, options?: RpcOptions): UnaryCall<ListReviewerReviewOptions, ReviewList>;
    /**
     * @generated from protobuf rpc: GetReview
     */
    getReview(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Review>;
    /**
     * @generated from protobuf rpc: CreateReview
     */
    createReview(input: Review, options?: RpcOptions): UnaryCall<Review, Review>;
    /**
     * @generated from protobuf rpc: UpdateReview
     */
    updateReview(input: Review, options?: RpcOptions): UnaryCall<Review, Review>;
    /**
     * @generated from protobuf rpc: CancelReview
     */
    cancelReview(input: CancelReviewRequest, options?: RpcOptions): UnaryCall<CancelReviewRequest, OperationResult>;
}
/**
 * @generated from protobuf service octelium.api.main.access.v1.ReviewerService
 */
export class ReviewerServiceClient implements IReviewerServiceClient, ServiceInfo {
    typeName = ReviewerService.typeName;
    methods = ReviewerService.methods;
    options = ReviewerService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetRequest
     */
    getRequest(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Request> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Request>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListRequest
     */
    listRequest(input: ListReviewerRequestOptions, options?: RpcOptions): UnaryCall<ListReviewerRequestOptions, RequestList> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListReviewerRequestOptions, RequestList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListReview
     */
    listReview(input: ListReviewerReviewOptions, options?: RpcOptions): UnaryCall<ListReviewerReviewOptions, ReviewList> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListReviewerReviewOptions, ReviewList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetReview
     */
    getReview(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Review> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Review>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateReview
     */
    createReview(input: Review, options?: RpcOptions): UnaryCall<Review, Review> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<Review, Review>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateReview
     */
    updateReview(input: Review, options?: RpcOptions): UnaryCall<Review, Review> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<Review, Review>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CancelReview
     */
    cancelReview(input: CancelReviewRequest, options?: RpcOptions): UnaryCall<CancelReviewRequest, OperationResult> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<CancelReviewRequest, OperationResult>("unary", this._transport, method, opt, input);
    }
}
