// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "apis/protobuf/main/visibilityv1/access/vaccessv1.proto" (package "octelium.api.main.visibility.access.v1", syntax proto3)
// tslint:disable
//
// Copyright (c) 2025-present Octelium Labs, LLC. All rights reserved.
//
// This software is licensed under the Octelium Enterprise Source-Available License.
// Commercial and production use is strictly prohibited without a valid
// Commercial Agreement from Octelium Labs, LLC.
//
// See the LICENSE file in the repository root for full license text.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ResourceService } from "./vaccessv1";
import type { ReviewList } from "../../accessv1/accessv1";
import type { ListReviewOptions } from "./vaccessv1";
import type { RequestList } from "../../accessv1/accessv1";
import type { ListRequestOptions } from "./vaccessv1";
import type { CatalogList } from "../../accessv1/accessv1";
import type { ListCatalogOptions } from "./vaccessv1";
import type { PolicyList } from "../../accessv1/accessv1";
import type { ListPolicyOptions } from "./vaccessv1";
import type { GetReviewSummaryResponse } from "./vaccessv1";
import type { GetReviewSummaryRequest } from "./vaccessv1";
import type { GetRequestSummaryResponse } from "./vaccessv1";
import type { GetRequestSummaryRequest } from "./vaccessv1";
import type { GetCatalogSummaryResponse } from "./vaccessv1";
import type { GetCatalogSummaryRequest } from "./vaccessv1";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetPolicySummaryResponse } from "./vaccessv1";
import type { GetPolicySummaryRequest } from "./vaccessv1";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service octelium.api.main.visibility.access.v1.ResourceService
 */
export interface IResourceServiceClient {
    /**
     * @generated from protobuf rpc: GetPolicySummary
     */
    getPolicySummary(input: GetPolicySummaryRequest, options?: RpcOptions): UnaryCall<GetPolicySummaryRequest, GetPolicySummaryResponse>;
    /**
     * @generated from protobuf rpc: GetCatalogSummary
     */
    getCatalogSummary(input: GetCatalogSummaryRequest, options?: RpcOptions): UnaryCall<GetCatalogSummaryRequest, GetCatalogSummaryResponse>;
    /**
     * @generated from protobuf rpc: GetRequestSummary
     */
    getRequestSummary(input: GetRequestSummaryRequest, options?: RpcOptions): UnaryCall<GetRequestSummaryRequest, GetRequestSummaryResponse>;
    /**
     * @generated from protobuf rpc: GetReviewSummary
     */
    getReviewSummary(input: GetReviewSummaryRequest, options?: RpcOptions): UnaryCall<GetReviewSummaryRequest, GetReviewSummaryResponse>;
    /**
     * @generated from protobuf rpc: ListPolicy
     */
    listPolicy(input: ListPolicyOptions, options?: RpcOptions): UnaryCall<ListPolicyOptions, PolicyList>;
    /**
     * @generated from protobuf rpc: ListCatalog
     */
    listCatalog(input: ListCatalogOptions, options?: RpcOptions): UnaryCall<ListCatalogOptions, CatalogList>;
    /**
     * @generated from protobuf rpc: ListRequest
     */
    listRequest(input: ListRequestOptions, options?: RpcOptions): UnaryCall<ListRequestOptions, RequestList>;
    /**
     * @generated from protobuf rpc: ListReview
     */
    listReview(input: ListReviewOptions, options?: RpcOptions): UnaryCall<ListReviewOptions, ReviewList>;
}
/**
 * @generated from protobuf service octelium.api.main.visibility.access.v1.ResourceService
 */
export class ResourceServiceClient implements IResourceServiceClient, ServiceInfo {
    typeName = ResourceService.typeName;
    methods = ResourceService.methods;
    options = ResourceService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetPolicySummary
     */
    getPolicySummary(input: GetPolicySummaryRequest, options?: RpcOptions): UnaryCall<GetPolicySummaryRequest, GetPolicySummaryResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPolicySummaryRequest, GetPolicySummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCatalogSummary
     */
    getCatalogSummary(input: GetCatalogSummaryRequest, options?: RpcOptions): UnaryCall<GetCatalogSummaryRequest, GetCatalogSummaryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCatalogSummaryRequest, GetCatalogSummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetRequestSummary
     */
    getRequestSummary(input: GetRequestSummaryRequest, options?: RpcOptions): UnaryCall<GetRequestSummaryRequest, GetRequestSummaryResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRequestSummaryRequest, GetRequestSummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetReviewSummary
     */
    getReviewSummary(input: GetReviewSummaryRequest, options?: RpcOptions): UnaryCall<GetReviewSummaryRequest, GetReviewSummaryResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetReviewSummaryRequest, GetReviewSummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListPolicy
     */
    listPolicy(input: ListPolicyOptions, options?: RpcOptions): UnaryCall<ListPolicyOptions, PolicyList> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListPolicyOptions, PolicyList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCatalog
     */
    listCatalog(input: ListCatalogOptions, options?: RpcOptions): UnaryCall<ListCatalogOptions, CatalogList> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCatalogOptions, CatalogList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListRequest
     */
    listRequest(input: ListRequestOptions, options?: RpcOptions): UnaryCall<ListRequestOptions, RequestList> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListRequestOptions, RequestList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListReview
     */
    listReview(input: ListReviewOptions, options?: RpcOptions): UnaryCall<ListReviewOptions, ReviewList> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListReviewOptions, ReviewList>("unary", this._transport, method, opt, input);
    }
}
