// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "apis/protobuf/main/visibilityv1/llm/vllmv1.proto" (package "octelium.api.main.visibility.llm.v1", syntax proto3)
// tslint:disable
//
// Copyright (c) 2025-present Octelium Labs, LLC. All rights reserved.
//
// This software is licensed under the Octelium Enterprise Source-Available License.
// Commercial and production use is strictly prohibited without a valid
// Commercial Agreement from Octelium Labs, LLC.
//
// See the LICENSE file in the repository root for full license text.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { LLMService } from "./vllmv1";
import type { ListAccessLogResponse } from "./vllmv1";
import type { ListAccessLogRequest } from "./vllmv1";
import type { ListTopPolicyResponse } from "./vllmv1";
import type { ListTopPolicyRequest } from "./vllmv1";
import type { ListTopServiceResponse } from "./vllmv1";
import type { ListTopServiceRequest } from "./vllmv1";
import type { ListTopSessionResponse } from "./vllmv1";
import type { ListTopSessionRequest } from "./vllmv1";
import type { ListTopUserResponse } from "./vllmv1";
import type { ListTopUserRequest } from "./vllmv1";
import type { ListTopToolResponse } from "./vllmv1";
import type { ListTopToolRequest } from "./vllmv1";
import type { ListTopModelResponse } from "./vllmv1";
import type { ListTopModelRequest } from "./vllmv1";
import type { ListTopDimensionResponse } from "./vllmv1";
import type { ListTopDimensionRequest } from "./vllmv1";
import type { GetDataPointResponse } from "./vllmv1";
import type { GetDataPointRequest } from "./vllmv1";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetSummaryResponse } from "./vllmv1";
import type { GetSummaryRequest } from "./vllmv1";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * LLMService is the visibility API of the LLM gateway mode. Every method of it
 * reads the LLM-specific AccessLog entries (i.e. the entries whose Info is an
 * `llm` one) and nothing else, so a Cluster that serves both LLM and non-LLM
 * Services never has to separate the two itself.
 *
 * The methods are deliberately shaped around a single Filter message and a
 * single Stats bundle: a dashboard builds one Filter from whatever the
 * administrator selected (a time range, a User, a model, a protocol, ...) and
 * passes that same Filter to every method of the page, and every method
 * answers with the same Stats fields so that a headline number, a chart series
 * and a table row are always the same measurement of the same set of entries.
 *
 * Note that a streamed request produces two AccessLog entries rather than one:
 * a STREAM_START entry when the first byte reaches the downstream and a
 * STREAM_END entry when the stream ends. The STREAM_END entry is the one that
 * carries the token usage, the finish reason and the called tools, while the
 * STREAM_START one carries only what was already known when the response
 * began. Every method therefore reads the terminal entries (i.e. COMPLETE and
 * STREAM_END) by default, which is exactly one entry per request. Read the
 * EntryScope enum before changing that default.
 *
 * @generated from protobuf service octelium.api.main.visibility.llm.v1.LLMService
 */
export interface ILLMServiceClient {
    /**
     * GetSummary is the headline measurement of the entries that the Filter
     * selects. It is what the top of a dashboard page reads.
     *
     * @generated from protobuf rpc: GetSummary
     */
    getSummary(input: GetSummaryRequest, options?: RpcOptions): UnaryCall<GetSummaryRequest, GetSummaryResponse>;
    /**
     * GetDataPoint is the time series of the entries that the Filter selects. It
     * is what a line or an area chart reads, and its GroupBy field is what turns
     * one series into one series per model, per User, per Session, per protocol
     * or per any other Dimension.
     *
     * @generated from protobuf rpc: GetDataPoint
     */
    getDataPoint(input: GetDataPointRequest, options?: RpcOptions): UnaryCall<GetDataPointRequest, GetDataPointResponse>;
    /**
     * ListTopDimension ranks the distinct values of a Dimension by a Metric. It
     * is the generic breakdown method: it is what a bar chart, a donut chart and
     * a leaderboard table read for every dimension that has no dedicated method
     * of its own.
     *
     * @generated from protobuf rpc: ListTopDimension
     */
    listTopDimension(input: ListTopDimensionRequest, options?: RpcOptions): UnaryCall<ListTopDimensionRequest, ListTopDimensionResponse>;
    /**
     * ListTopModel ranks the models. It is a dedicated method rather than a
     * Dimension since a model row is read against three different model names of
     * an entry (i.e. the requested, the effective and the reported one) and
     * since seeing the three counts side by side is what shows how often the
     * Cluster served something other than what was asked for.
     *
     * @generated from protobuf rpc: ListTopModel
     */
    listTopModel(input: ListTopModelRequest, options?: RpcOptions): UnaryCall<ListTopModelRequest, ListTopModelResponse>;
    /**
     * ListTopTool ranks the tools. It is a dedicated method rather than a
     * Dimension since a tool row carries the number of the requests that offered
     * the tool, the number of the requests whose model asked to invoke it and
     * the number of the requests from which a Tools Plugin removed it, which are
     * three different groupings of three different fields.
     *
     * @generated from protobuf rpc: ListTopTool
     */
    listTopTool(input: ListTopToolRequest, options?: RpcOptions): UnaryCall<ListTopToolRequest, ListTopToolResponse>;
    /**
     * ListTopUser ranks the Users, which is what shows who consumes the
     * inference budget of the Cluster.
     *
     * @generated from protobuf rpc: ListTopUser
     */
    listTopUser(input: ListTopUserRequest, options?: RpcOptions): UnaryCall<ListTopUserRequest, ListTopUserResponse>;
    /**
     * ListTopSession ranks the Sessions, which is the per-credential and
     * per-workload view of the same consumption that ListTopUser shows per
     * identity.
     *
     * @generated from protobuf rpc: ListTopSession
     */
    listTopSession(input: ListTopSessionRequest, options?: RpcOptions): UnaryCall<ListTopSessionRequest, ListTopSessionResponse>;
    /**
     * ListTopService ranks the LLM Services.
     *
     * @generated from protobuf rpc: ListTopService
     */
    listTopService(input: ListTopServiceRequest, options?: RpcOptions): UnaryCall<ListTopServiceRequest, ListTopServiceResponse>;
    /**
     * ListTopPolicy ranks the Policies whose rules decided the authorization of
     * the entries.
     *
     * @generated from protobuf rpc: ListTopPolicy
     */
    listTopPolicy(input: ListTopPolicyRequest, options?: RpcOptions): UnaryCall<ListTopPolicyRequest, ListTopPolicyResponse>;
    /**
     * ListAccessLog lists the LLM AccessLog entries themselves. It is what a
     * request explorer table reads, and unlike the generic
     * `octelium.api.main.visibility.v1.AccessLogService.ListAccessLog` method it
     * filters by the LLM-specific dimensions and orders by the LLM-specific
     * measurements (e.g. the 20 slowest requests of a model, or every request
     * that a Guardrail denied).
     *
     * @generated from protobuf rpc: ListAccessLog
     */
    listAccessLog(input: ListAccessLogRequest, options?: RpcOptions): UnaryCall<ListAccessLogRequest, ListAccessLogResponse>;
}
/**
 * LLMService is the visibility API of the LLM gateway mode. Every method of it
 * reads the LLM-specific AccessLog entries (i.e. the entries whose Info is an
 * `llm` one) and nothing else, so a Cluster that serves both LLM and non-LLM
 * Services never has to separate the two itself.
 *
 * The methods are deliberately shaped around a single Filter message and a
 * single Stats bundle: a dashboard builds one Filter from whatever the
 * administrator selected (a time range, a User, a model, a protocol, ...) and
 * passes that same Filter to every method of the page, and every method
 * answers with the same Stats fields so that a headline number, a chart series
 * and a table row are always the same measurement of the same set of entries.
 *
 * Note that a streamed request produces two AccessLog entries rather than one:
 * a STREAM_START entry when the first byte reaches the downstream and a
 * STREAM_END entry when the stream ends. The STREAM_END entry is the one that
 * carries the token usage, the finish reason and the called tools, while the
 * STREAM_START one carries only what was already known when the response
 * began. Every method therefore reads the terminal entries (i.e. COMPLETE and
 * STREAM_END) by default, which is exactly one entry per request. Read the
 * EntryScope enum before changing that default.
 *
 * @generated from protobuf service octelium.api.main.visibility.llm.v1.LLMService
 */
export class LLMServiceClient implements ILLMServiceClient, ServiceInfo {
    typeName = LLMService.typeName;
    methods = LLMService.methods;
    options = LLMService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * GetSummary is the headline measurement of the entries that the Filter
     * selects. It is what the top of a dashboard page reads.
     *
     * @generated from protobuf rpc: GetSummary
     */
    getSummary(input: GetSummaryRequest, options?: RpcOptions): UnaryCall<GetSummaryRequest, GetSummaryResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSummaryRequest, GetSummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * GetDataPoint is the time series of the entries that the Filter selects. It
     * is what a line or an area chart reads, and its GroupBy field is what turns
     * one series into one series per model, per User, per Session, per protocol
     * or per any other Dimension.
     *
     * @generated from protobuf rpc: GetDataPoint
     */
    getDataPoint(input: GetDataPointRequest, options?: RpcOptions): UnaryCall<GetDataPointRequest, GetDataPointResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDataPointRequest, GetDataPointResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListTopDimension ranks the distinct values of a Dimension by a Metric. It
     * is the generic breakdown method: it is what a bar chart, a donut chart and
     * a leaderboard table read for every dimension that has no dedicated method
     * of its own.
     *
     * @generated from protobuf rpc: ListTopDimension
     */
    listTopDimension(input: ListTopDimensionRequest, options?: RpcOptions): UnaryCall<ListTopDimensionRequest, ListTopDimensionResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTopDimensionRequest, ListTopDimensionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListTopModel ranks the models. It is a dedicated method rather than a
     * Dimension since a model row is read against three different model names of
     * an entry (i.e. the requested, the effective and the reported one) and
     * since seeing the three counts side by side is what shows how often the
     * Cluster served something other than what was asked for.
     *
     * @generated from protobuf rpc: ListTopModel
     */
    listTopModel(input: ListTopModelRequest, options?: RpcOptions): UnaryCall<ListTopModelRequest, ListTopModelResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTopModelRequest, ListTopModelResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListTopTool ranks the tools. It is a dedicated method rather than a
     * Dimension since a tool row carries the number of the requests that offered
     * the tool, the number of the requests whose model asked to invoke it and
     * the number of the requests from which a Tools Plugin removed it, which are
     * three different groupings of three different fields.
     *
     * @generated from protobuf rpc: ListTopTool
     */
    listTopTool(input: ListTopToolRequest, options?: RpcOptions): UnaryCall<ListTopToolRequest, ListTopToolResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTopToolRequest, ListTopToolResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListTopUser ranks the Users, which is what shows who consumes the
     * inference budget of the Cluster.
     *
     * @generated from protobuf rpc: ListTopUser
     */
    listTopUser(input: ListTopUserRequest, options?: RpcOptions): UnaryCall<ListTopUserRequest, ListTopUserResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTopUserRequest, ListTopUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListTopSession ranks the Sessions, which is the per-credential and
     * per-workload view of the same consumption that ListTopUser shows per
     * identity.
     *
     * @generated from protobuf rpc: ListTopSession
     */
    listTopSession(input: ListTopSessionRequest, options?: RpcOptions): UnaryCall<ListTopSessionRequest, ListTopSessionResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTopSessionRequest, ListTopSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListTopService ranks the LLM Services.
     *
     * @generated from protobuf rpc: ListTopService
     */
    listTopService(input: ListTopServiceRequest, options?: RpcOptions): UnaryCall<ListTopServiceRequest, ListTopServiceResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTopServiceRequest, ListTopServiceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListTopPolicy ranks the Policies whose rules decided the authorization of
     * the entries.
     *
     * @generated from protobuf rpc: ListTopPolicy
     */
    listTopPolicy(input: ListTopPolicyRequest, options?: RpcOptions): UnaryCall<ListTopPolicyRequest, ListTopPolicyResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListTopPolicyRequest, ListTopPolicyResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * ListAccessLog lists the LLM AccessLog entries themselves. It is what a
     * request explorer table reads, and unlike the generic
     * `octelium.api.main.visibility.v1.AccessLogService.ListAccessLog` method it
     * filters by the LLM-specific dimensions and orders by the LLM-specific
     * measurements (e.g. the 20 slowest requests of a model, or every request
     * that a Guardrail denied).
     *
     * @generated from protobuf rpc: ListAccessLog
     */
    listAccessLog(input: ListAccessLogRequest, options?: RpcOptions): UnaryCall<ListAccessLogRequest, ListAccessLogResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAccessLogRequest, ListAccessLogResponse>("unary", this._transport, method, opt, input);
    }
}
