// Copyright (c) 2025-present Octelium Labs, LLC. All rights reserved.
//
// This software is licensed under the Octelium Enterprise Source-Available License.
// Commercial and production use is strictly prohibited without a valid
// Commercial Agreement from Octelium Labs, LLC.
//
// See the LICENSE file in the repository root for full license text.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: cclusterv1.proto

package cclusterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterConnInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveIndexesWG   []uint32               `protobuf:"varint,1,rep,packed,name=activeIndexesWG,proto3" json:"activeIndexesWG,omitempty"`
	ActiveIndexesQUIC []uint32               `protobuf:"varint,2,rep,packed,name=activeIndexesQUIC,proto3" json:"activeIndexesQUIC,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClusterConnInfo) Reset() {
	*x = ClusterConnInfo{}
	mi := &file_cclusterv1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConnInfo) ProtoMessage() {}

func (x *ClusterConnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cclusterv1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConnInfo.ProtoReflect.Descriptor instead.
func (*ClusterConnInfo) Descriptor() ([]byte, []int) {
	return file_cclusterv1_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterConnInfo) GetActiveIndexesWG() []uint32 {
	if x != nil {
		return x.ActiveIndexesWG
	}
	return nil
}

func (x *ClusterConnInfo) GetActiveIndexesQUIC() []uint32 {
	if x != nil {
		return x.ActiveIndexesQUIC
	}
	return nil
}

var File_cclusterv1_proto protoreflect.FileDescriptor

var file_cclusterv1_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1f, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x22, 0x69, 0x0a, 0x0f, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x57, 0x47, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x57, 0x47,
	0x12, 0x2c, 0x0a, 0x11, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65,
	0x73, 0x51, 0x55, 0x49, 0x43, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x11, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x51, 0x55, 0x49, 0x43, 0x42, 0x36,
	0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x63, 0x74,
	0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2f, 0x6f, 0x63, 0x74, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2f, 0x61,
	0x70, 0x69, 0x73, 0x2f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cclusterv1_proto_rawDescOnce sync.Once
	file_cclusterv1_proto_rawDescData = file_cclusterv1_proto_rawDesc
)

func file_cclusterv1_proto_rawDescGZIP() []byte {
	file_cclusterv1_proto_rawDescOnce.Do(func() {
		file_cclusterv1_proto_rawDescData = protoimpl.X.CompressGZIP(file_cclusterv1_proto_rawDescData)
	})
	return file_cclusterv1_proto_rawDescData
}

var file_cclusterv1_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cclusterv1_proto_goTypes = []any{
	(*ClusterConnInfo)(nil), // 0: octelium.api.cluster.cluster.v1.ClusterConnInfo
}
var file_cclusterv1_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cclusterv1_proto_init() }
func file_cclusterv1_proto_init() {
	if File_cclusterv1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cclusterv1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cclusterv1_proto_goTypes,
		DependencyIndexes: file_cclusterv1_proto_depIdxs,
		MessageInfos:      file_cclusterv1_proto_msgTypes,
	}.Build()
	File_cclusterv1_proto = out.File
	file_cclusterv1_proto_rawDesc = nil
	file_cclusterv1_proto_goTypes = nil
	file_cclusterv1_proto_depIdxs = nil
}
