// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "apis/protobuf/main/enterprisev1/enterprisev1.proto" (package "octelium.api.main.enterprise.v1", syntax proto3)
// tslint:disable
//
// Copyright (c) 2025-present Octelium Labs, LLC. All rights reserved.
//
// This software is licensed under the Octelium Enterprise Source-Available
// License. Commercial and production use is strictly prohibited without a valid
// Commercial Agreement from Octelium Labs, LLC.
//
// See the LICENSE file in the repository root for full license text.
//
import { ClusterService } from "./enterprisev1";
import type { UpgradeClusterResponse } from "./enterprisev1";
import type { UpgradeClusterRequest } from "./enterprisev1";
import { PolicyPortalService } from "./enterprisev1";
import type { IsAuthorizedResponse } from "./enterprisev1";
import type { IsAuthorizedRequest } from "./enterprisev1";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { MainService } from "./enterprisev1";
import type { Condition as Condition$ } from "../corev1/corev1";
import type { Condition } from "./enterprisev1";
import type { DeviceManagerList } from "./enterprisev1";
import type { ListDeviceManagerOptions } from "./enterprisev1";
import type { DeviceManager } from "./enterprisev1";
import type { SecretStoreList } from "./enterprisev1";
import type { ListSecretStoreOptions } from "./enterprisev1";
import type { SecretStore } from "./enterprisev1";
import type { SecretList } from "./enterprisev1";
import type { ListSecretOptions } from "./enterprisev1";
import type { Secret } from "./enterprisev1";
import type { SynchronizeDirectoryProviderResponse } from "./enterprisev1";
import type { SynchronizeDirectoryProviderRequest } from "./enterprisev1";
import type { DirectoryProviderGroupList } from "./enterprisev1";
import type { ListDirectoryProviderGroupOptions } from "./enterprisev1";
import type { DirectoryProviderUserList } from "./enterprisev1";
import type { ListDirectoryProviderUserOptions } from "./enterprisev1";
import type { GenerateDirectoryProviderCredentialResponse } from "./enterprisev1";
import type { GenerateDirectoryProviderCredentialRequest } from "./enterprisev1";
import type { DirectoryProviderList } from "./enterprisev1";
import type { ListDirectoryProviderOptions } from "./enterprisev1";
import type { DirectoryProvider } from "./enterprisev1";
import type { CertificateIssuerList } from "./enterprisev1";
import type { ListCertificateIssuerOptions } from "./enterprisev1";
import type { CertificateIssuer } from "./enterprisev1";
import type { IssueCertificateResponse } from "./enterprisev1";
import type { IssueCertificateRequest } from "./enterprisev1";
import type { CertificateList } from "./enterprisev1";
import type { ListCertificateOptions } from "./enterprisev1";
import type { Certificate } from "./enterprisev1";
import type { DNSProviderList } from "./enterprisev1";
import type { ListDNSProviderOptions } from "./enterprisev1";
import type { DNSProvider } from "./enterprisev1";
import type { OperationResult } from "../metav1/metav1";
import type { DeleteOptions } from "../metav1/metav1";
import type { CollectorExporterList } from "./enterprisev1";
import type { ListCollectorExporterOptions } from "./enterprisev1";
import type { GetOptions } from "../metav1/metav1";
import type { CollectorExporter } from "./enterprisev1";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ClusterConfig } from "./enterprisev1";
import type { GetClusterConfigRequest } from "./enterprisev1";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service octelium.api.main.enterprise.v1.MainService
 */
export interface IMainServiceClient {
    /**
     * GetClusterConfig gets the Cluster Configuration.
     *
     * @generated from protobuf rpc: GetClusterConfig
     */
    getClusterConfig(input: GetClusterConfigRequest, options?: RpcOptions): UnaryCall<GetClusterConfigRequest, ClusterConfig>;
    /**
     * UpdateConfig updates the Cluster Configuration.
     *
     * @generated from protobuf rpc: UpdateClusterConfig
     */
    updateClusterConfig(input: ClusterConfig, options?: RpcOptions): UnaryCall<ClusterConfig, ClusterConfig>;
    /**
     * @generated from protobuf rpc: CreateCollectorExporter
     */
    createCollectorExporter(input: CollectorExporter, options?: RpcOptions): UnaryCall<CollectorExporter, CollectorExporter>;
    /**
     * @generated from protobuf rpc: GetCollectorExporter
     */
    getCollectorExporter(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, CollectorExporter>;
    /**
     * @generated from protobuf rpc: ListCollectorExporter
     */
    listCollectorExporter(input: ListCollectorExporterOptions, options?: RpcOptions): UnaryCall<ListCollectorExporterOptions, CollectorExporterList>;
    /**
     * @generated from protobuf rpc: UpdateCollectorExporter
     */
    updateCollectorExporter(input: CollectorExporter, options?: RpcOptions): UnaryCall<CollectorExporter, CollectorExporter>;
    /**
     * @generated from protobuf rpc: DeleteCollectorExporter
     */
    deleteCollectorExporter(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * rpc CreateDNSProvider(DNSProvider) returns (DNSProvider) {}
     *
     * @generated from protobuf rpc: GetDNSProvider
     */
    getDNSProvider(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, DNSProvider>;
    /**
     * @generated from protobuf rpc: ListDNSProvider
     */
    listDNSProvider(input: ListDNSProviderOptions, options?: RpcOptions): UnaryCall<ListDNSProviderOptions, DNSProviderList>;
    /**
     * @generated from protobuf rpc: UpdateDNSProvider
     */
    updateDNSProvider(input: DNSProvider, options?: RpcOptions): UnaryCall<DNSProvider, DNSProvider>;
    /**
     * rpc CreateCertificate(Certificate) returns (Certificate) {}
     *
     * @generated from protobuf rpc: GetCertificate
     */
    getCertificate(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Certificate>;
    /**
     * @generated from protobuf rpc: UpdateCertificate
     */
    updateCertificate(input: Certificate, options?: RpcOptions): UnaryCall<Certificate, Certificate>;
    /**
     * @generated from protobuf rpc: ListCertificate
     */
    listCertificate(input: ListCertificateOptions, options?: RpcOptions): UnaryCall<ListCertificateOptions, CertificateList>;
    /**
     * @generated from protobuf rpc: IssueCertificate
     */
    issueCertificate(input: IssueCertificateRequest, options?: RpcOptions): UnaryCall<IssueCertificateRequest, IssueCertificateResponse>;
    /**
     * rpc CreateCertificateIssuer(CertificateIssuer) returns (CertificateIssuer)
     * {}
     *
     * @generated from protobuf rpc: GetCertificateIssuer
     */
    getCertificateIssuer(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, CertificateIssuer>;
    /**
     * @generated from protobuf rpc: ListCertificateIssuer
     */
    listCertificateIssuer(input: ListCertificateIssuerOptions, options?: RpcOptions): UnaryCall<ListCertificateIssuerOptions, CertificateIssuerList>;
    /**
     * @generated from protobuf rpc: UpdateCertificateIssuer
     */
    updateCertificateIssuer(input: CertificateIssuer, options?: RpcOptions): UnaryCall<CertificateIssuer, CertificateIssuer>;
    /**
     * @generated from protobuf rpc: CreateDirectoryProvider
     */
    createDirectoryProvider(input: DirectoryProvider, options?: RpcOptions): UnaryCall<DirectoryProvider, DirectoryProvider>;
    /**
     * @generated from protobuf rpc: GetDirectoryProvider
     */
    getDirectoryProvider(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, DirectoryProvider>;
    /**
     * @generated from protobuf rpc: ListDirectoryProvider
     */
    listDirectoryProvider(input: ListDirectoryProviderOptions, options?: RpcOptions): UnaryCall<ListDirectoryProviderOptions, DirectoryProviderList>;
    /**
     * @generated from protobuf rpc: UpdateDirectoryProvider
     */
    updateDirectoryProvider(input: DirectoryProvider, options?: RpcOptions): UnaryCall<DirectoryProvider, DirectoryProvider>;
    /**
     * @generated from protobuf rpc: DeleteDirectoryProvider
     */
    deleteDirectoryProvider(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * @generated from protobuf rpc: GenerateDirectoryProviderCredential
     */
    generateDirectoryProviderCredential(input: GenerateDirectoryProviderCredentialRequest, options?: RpcOptions): UnaryCall<GenerateDirectoryProviderCredentialRequest, GenerateDirectoryProviderCredentialResponse>;
    /**
     * @generated from protobuf rpc: ListDirectoryProviderUser
     */
    listDirectoryProviderUser(input: ListDirectoryProviderUserOptions, options?: RpcOptions): UnaryCall<ListDirectoryProviderUserOptions, DirectoryProviderUserList>;
    /**
     * @generated from protobuf rpc: ListDirectoryProviderGroup
     */
    listDirectoryProviderGroup(input: ListDirectoryProviderGroupOptions, options?: RpcOptions): UnaryCall<ListDirectoryProviderGroupOptions, DirectoryProviderGroupList>;
    /**
     * @generated from protobuf rpc: SynchronizeDirectoryProvider
     */
    synchronizeDirectoryProvider(input: SynchronizeDirectoryProviderRequest, options?: RpcOptions): UnaryCall<SynchronizeDirectoryProviderRequest, SynchronizeDirectoryProviderResponse>;
    /**
     * CreateSecret creates a Secret
     *
     * @generated from protobuf rpc: CreateSecret
     */
    createSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret>;
    /**
     * ListSecret lists Secrets
     *
     * @generated from protobuf rpc: ListSecret
     */
    listSecret(input: ListSecretOptions, options?: RpcOptions): UnaryCall<ListSecretOptions, SecretList>;
    /**
     * DeleteSecret deletes a Secret
     *
     * @generated from protobuf rpc: DeleteSecret
     */
    deleteSecret(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * GetSecret retrieves a specific Secret
     *
     * @generated from protobuf rpc: GetSecret
     */
    getSecret(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Secret>;
    /**
     * UpdateSecret creates a Secret
     *
     * @generated from protobuf rpc: UpdateSecret
     */
    updateSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret>;
    /**
     * rpc CreateSecretStore(SecretStore) returns (SecretStore) {}
     *
     * @generated from protobuf rpc: GetSecretStore
     */
    getSecretStore(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, SecretStore>;
    /**
     * @generated from protobuf rpc: ListSecretStore
     */
    listSecretStore(input: ListSecretStoreOptions, options?: RpcOptions): UnaryCall<ListSecretStoreOptions, SecretStoreList>;
    /**
     * @generated from protobuf rpc: UpdateSecretStore
     */
    updateSecretStore(input: SecretStore, options?: RpcOptions): UnaryCall<SecretStore, SecretStore>;
    /**
     * @generated from protobuf rpc: CreateDeviceManager
     */
    createDeviceManager(input: DeviceManager, options?: RpcOptions): UnaryCall<DeviceManager, DeviceManager>;
    /**
     * @generated from protobuf rpc: GetDeviceManager
     */
    getDeviceManager(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, DeviceManager>;
    /**
     * @generated from protobuf rpc: ListDeviceManager
     */
    listDeviceManager(input: ListDeviceManagerOptions, options?: RpcOptions): UnaryCall<ListDeviceManagerOptions, DeviceManagerList>;
    /**
     * @generated from protobuf rpc: UpdateDeviceManager
     */
    updateDeviceManager(input: DeviceManager, options?: RpcOptions): UnaryCall<DeviceManager, DeviceManager>;
    /**
     * @generated from protobuf rpc: DeleteDeviceManager
     */
    deleteDeviceManager(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult>;
    /**
     * @generated from protobuf rpc: GetCoreCondition
     */
    getCoreCondition(input: Condition, options?: RpcOptions): UnaryCall<Condition, Condition$>;
}
/**
 * @generated from protobuf service octelium.api.main.enterprise.v1.MainService
 */
export class MainServiceClient implements IMainServiceClient, ServiceInfo {
    typeName = MainService.typeName;
    methods = MainService.methods;
    options = MainService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * GetClusterConfig gets the Cluster Configuration.
     *
     * @generated from protobuf rpc: GetClusterConfig
     */
    getClusterConfig(input: GetClusterConfigRequest, options?: RpcOptions): UnaryCall<GetClusterConfigRequest, ClusterConfig> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetClusterConfigRequest, ClusterConfig>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateConfig updates the Cluster Configuration.
     *
     * @generated from protobuf rpc: UpdateClusterConfig
     */
    updateClusterConfig(input: ClusterConfig, options?: RpcOptions): UnaryCall<ClusterConfig, ClusterConfig> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClusterConfig, ClusterConfig>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateCollectorExporter
     */
    createCollectorExporter(input: CollectorExporter, options?: RpcOptions): UnaryCall<CollectorExporter, CollectorExporter> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CollectorExporter, CollectorExporter>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCollectorExporter
     */
    getCollectorExporter(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, CollectorExporter> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, CollectorExporter>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCollectorExporter
     */
    listCollectorExporter(input: ListCollectorExporterOptions, options?: RpcOptions): UnaryCall<ListCollectorExporterOptions, CollectorExporterList> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCollectorExporterOptions, CollectorExporterList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateCollectorExporter
     */
    updateCollectorExporter(input: CollectorExporter, options?: RpcOptions): UnaryCall<CollectorExporter, CollectorExporter> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<CollectorExporter, CollectorExporter>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteCollectorExporter
     */
    deleteCollectorExporter(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * rpc CreateDNSProvider(DNSProvider) returns (DNSProvider) {}
     *
     * @generated from protobuf rpc: GetDNSProvider
     */
    getDNSProvider(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, DNSProvider> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, DNSProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListDNSProvider
     */
    listDNSProvider(input: ListDNSProviderOptions, options?: RpcOptions): UnaryCall<ListDNSProviderOptions, DNSProviderList> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDNSProviderOptions, DNSProviderList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateDNSProvider
     */
    updateDNSProvider(input: DNSProvider, options?: RpcOptions): UnaryCall<DNSProvider, DNSProvider> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<DNSProvider, DNSProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * rpc CreateCertificate(Certificate) returns (Certificate) {}
     *
     * @generated from protobuf rpc: GetCertificate
     */
    getCertificate(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Certificate> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Certificate>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateCertificate
     */
    updateCertificate(input: Certificate, options?: RpcOptions): UnaryCall<Certificate, Certificate> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<Certificate, Certificate>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCertificate
     */
    listCertificate(input: ListCertificateOptions, options?: RpcOptions): UnaryCall<ListCertificateOptions, CertificateList> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCertificateOptions, CertificateList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: IssueCertificate
     */
    issueCertificate(input: IssueCertificateRequest, options?: RpcOptions): UnaryCall<IssueCertificateRequest, IssueCertificateResponse> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<IssueCertificateRequest, IssueCertificateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * rpc CreateCertificateIssuer(CertificateIssuer) returns (CertificateIssuer)
     * {}
     *
     * @generated from protobuf rpc: GetCertificateIssuer
     */
    getCertificateIssuer(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, CertificateIssuer> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, CertificateIssuer>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListCertificateIssuer
     */
    listCertificateIssuer(input: ListCertificateIssuerOptions, options?: RpcOptions): UnaryCall<ListCertificateIssuerOptions, CertificateIssuerList> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListCertificateIssuerOptions, CertificateIssuerList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateCertificateIssuer
     */
    updateCertificateIssuer(input: CertificateIssuer, options?: RpcOptions): UnaryCall<CertificateIssuer, CertificateIssuer> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<CertificateIssuer, CertificateIssuer>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateDirectoryProvider
     */
    createDirectoryProvider(input: DirectoryProvider, options?: RpcOptions): UnaryCall<DirectoryProvider, DirectoryProvider> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<DirectoryProvider, DirectoryProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDirectoryProvider
     */
    getDirectoryProvider(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, DirectoryProvider> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, DirectoryProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListDirectoryProvider
     */
    listDirectoryProvider(input: ListDirectoryProviderOptions, options?: RpcOptions): UnaryCall<ListDirectoryProviderOptions, DirectoryProviderList> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDirectoryProviderOptions, DirectoryProviderList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateDirectoryProvider
     */
    updateDirectoryProvider(input: DirectoryProvider, options?: RpcOptions): UnaryCall<DirectoryProvider, DirectoryProvider> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<DirectoryProvider, DirectoryProvider>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteDirectoryProvider
     */
    deleteDirectoryProvider(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GenerateDirectoryProviderCredential
     */
    generateDirectoryProviderCredential(input: GenerateDirectoryProviderCredentialRequest, options?: RpcOptions): UnaryCall<GenerateDirectoryProviderCredentialRequest, GenerateDirectoryProviderCredentialResponse> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<GenerateDirectoryProviderCredentialRequest, GenerateDirectoryProviderCredentialResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListDirectoryProviderUser
     */
    listDirectoryProviderUser(input: ListDirectoryProviderUserOptions, options?: RpcOptions): UnaryCall<ListDirectoryProviderUserOptions, DirectoryProviderUserList> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDirectoryProviderUserOptions, DirectoryProviderUserList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListDirectoryProviderGroup
     */
    listDirectoryProviderGroup(input: ListDirectoryProviderGroupOptions, options?: RpcOptions): UnaryCall<ListDirectoryProviderGroupOptions, DirectoryProviderGroupList> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDirectoryProviderGroupOptions, DirectoryProviderGroupList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SynchronizeDirectoryProvider
     */
    synchronizeDirectoryProvider(input: SynchronizeDirectoryProviderRequest, options?: RpcOptions): UnaryCall<SynchronizeDirectoryProviderRequest, SynchronizeDirectoryProviderResponse> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<SynchronizeDirectoryProviderRequest, SynchronizeDirectoryProviderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * CreateSecret creates a Secret
     *
     * @generated from protobuf rpc: CreateSecret
     */
    createSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<Secret, Secret>("unary", this._transport, method, opt, input);
    }
    /**
     * ListSecret lists Secrets
     *
     * @generated from protobuf rpc: ListSecret
     */
    listSecret(input: ListSecretOptions, options?: RpcOptions): UnaryCall<ListSecretOptions, SecretList> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSecretOptions, SecretList>("unary", this._transport, method, opt, input);
    }
    /**
     * DeleteSecret deletes a Secret
     *
     * @generated from protobuf rpc: DeleteSecret
     */
    deleteSecret(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * GetSecret retrieves a specific Secret
     *
     * @generated from protobuf rpc: GetSecret
     */
    getSecret(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, Secret> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, Secret>("unary", this._transport, method, opt, input);
    }
    /**
     * UpdateSecret creates a Secret
     *
     * @generated from protobuf rpc: UpdateSecret
     */
    updateSecret(input: Secret, options?: RpcOptions): UnaryCall<Secret, Secret> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<Secret, Secret>("unary", this._transport, method, opt, input);
    }
    /**
     * rpc CreateSecretStore(SecretStore) returns (SecretStore) {}
     *
     * @generated from protobuf rpc: GetSecretStore
     */
    getSecretStore(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, SecretStore> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, SecretStore>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSecretStore
     */
    listSecretStore(input: ListSecretStoreOptions, options?: RpcOptions): UnaryCall<ListSecretStoreOptions, SecretStoreList> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSecretStoreOptions, SecretStoreList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateSecretStore
     */
    updateSecretStore(input: SecretStore, options?: RpcOptions): UnaryCall<SecretStore, SecretStore> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<SecretStore, SecretStore>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateDeviceManager
     */
    createDeviceManager(input: DeviceManager, options?: RpcOptions): UnaryCall<DeviceManager, DeviceManager> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeviceManager, DeviceManager>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetDeviceManager
     */
    getDeviceManager(input: GetOptions, options?: RpcOptions): UnaryCall<GetOptions, DeviceManager> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOptions, DeviceManager>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListDeviceManager
     */
    listDeviceManager(input: ListDeviceManagerOptions, options?: RpcOptions): UnaryCall<ListDeviceManagerOptions, DeviceManagerList> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListDeviceManagerOptions, DeviceManagerList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateDeviceManager
     */
    updateDeviceManager(input: DeviceManager, options?: RpcOptions): UnaryCall<DeviceManager, DeviceManager> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeviceManager, DeviceManager>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteDeviceManager
     */
    deleteDeviceManager(input: DeleteOptions, options?: RpcOptions): UnaryCall<DeleteOptions, OperationResult> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteOptions, OperationResult>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetCoreCondition
     */
    getCoreCondition(input: Condition, options?: RpcOptions): UnaryCall<Condition, Condition$> {
        const method = this.methods[39], opt = this._transport.mergeOptions(options);
        return stackIntercept<Condition, Condition$>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service octelium.api.main.enterprise.v1.PolicyPortalService
 */
export interface IPolicyPortalServiceClient {
    /**
     * @generated from protobuf rpc: IsAuthorized
     */
    isAuthorized(input: IsAuthorizedRequest, options?: RpcOptions): UnaryCall<IsAuthorizedRequest, IsAuthorizedResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.enterprise.v1.PolicyPortalService
 */
export class PolicyPortalServiceClient implements IPolicyPortalServiceClient, ServiceInfo {
    typeName = PolicyPortalService.typeName;
    methods = PolicyPortalService.methods;
    options = PolicyPortalService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: IsAuthorized
     */
    isAuthorized(input: IsAuthorizedRequest, options?: RpcOptions): UnaryCall<IsAuthorizedRequest, IsAuthorizedResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<IsAuthorizedRequest, IsAuthorizedResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service octelium.api.main.enterprise.v1.ClusterService
 */
export interface IClusterServiceClient {
    /**
     * @generated from protobuf rpc: UpgradeCluster
     */
    upgradeCluster(input: UpgradeClusterRequest, options?: RpcOptions): UnaryCall<UpgradeClusterRequest, UpgradeClusterResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.enterprise.v1.ClusterService
 */
export class ClusterServiceClient implements IClusterServiceClient, ServiceInfo {
    typeName = ClusterService.typeName;
    methods = ClusterService.methods;
    options = ClusterService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: UpgradeCluster
     */
    upgradeCluster(input: UpgradeClusterRequest, options?: RpcOptions): UnaryCall<UpgradeClusterRequest, UpgradeClusterResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpgradeClusterRequest, UpgradeClusterResponse>("unary", this._transport, method, opt, input);
    }
}
