// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "apis/protobuf/main/visibilityv1/visibilityv1.proto" (package "octelium.api.main.visibility.v1", syntax proto3)
// tslint:disable
//
// Copyright (c) 2025-present Octelium Labs, LLC. All rights reserved.
//
// This software is licensed under the Octelium Enterprise Source-Available
// License. Commercial and production use is strictly prohibited without a valid
// Commercial Agreement from Octelium Labs, LLC.
//
// See the LICENSE file in the repository root for full license text.
//
import { MetricsService } from "./visibilityv1";
import type { GetHistogramResponse } from "./visibilityv1";
import type { GetHistogramRequest } from "./visibilityv1";
import type { GetGaugeResponse } from "./visibilityv1";
import type { GetGaugeRequest } from "./visibilityv1";
import type { GetCounterResponse } from "./visibilityv1";
import type { GetCounterRequest } from "./visibilityv1";
import { ComponentLogService } from "./visibilityv1";
import type { GetComponentLogDataPointResponse } from "./visibilityv1";
import type { GetComponentLogDataPointRequest } from "./visibilityv1";
import type { GetComponentLogSummaryResponse } from "./visibilityv1";
import type { GetComponentLogSummaryRequest } from "./visibilityv1";
import type { ListComponentLogResponse } from "./visibilityv1";
import type { ListComponentLogRequest } from "./visibilityv1";
import { AuditLogService } from "./visibilityv1";
import type { ListAuditLogTopSessionResponse } from "./visibilityv1";
import type { ListAuditLogTopSessionRequest } from "./visibilityv1";
import type { ListAuditLogTopUserResponse } from "./visibilityv1";
import type { ListAuditLogTopUserRequest } from "./visibilityv1";
import type { GetAuditLogDataPointResponse } from "./visibilityv1";
import type { GetAuditLogDataPointRequest } from "./visibilityv1";
import type { GetAuditLogSummaryResponse } from "./visibilityv1";
import type { GetAuditLogSummaryRequest } from "./visibilityv1";
import type { ListAuditLogResponse } from "./visibilityv1";
import type { ListAuditLogRequest } from "./visibilityv1";
import { AuthenticationLogService } from "./visibilityv1";
import type { ListAuthenticationLogTopIdentityProviderResponse } from "./visibilityv1";
import type { ListAuthenticationLogTopIdentityProviderRequest } from "./visibilityv1";
import type { ListAuthenticationLogTopCredentialResponse } from "./visibilityv1";
import type { ListAuthenticationLogTopCredentialRequest } from "./visibilityv1";
import type { ListAuthenticationLogTopUserResponse } from "./visibilityv1";
import type { ListAuthenticationLogTopUserRequest } from "./visibilityv1";
import type { GetAuthenticationLogDataPointResponse } from "./visibilityv1";
import type { GetAuthenticationLogDataPointRequest } from "./visibilityv1";
import type { GetAuthenticationLogSummaryResponse } from "./visibilityv1";
import type { GetAuthenticationLogSummaryRequest } from "./visibilityv1";
import type { ListAuthenticationLogResponse } from "./visibilityv1";
import type { ListAuthenticationLogRequest } from "./visibilityv1";
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AccessLogService } from "./visibilityv1";
import type { ListAccessLogTopPolicyResponse } from "./visibilityv1";
import type { ListAccessLogTopPolicyRequest } from "./visibilityv1";
import type { ListAccessLogTopSessionResponse } from "./visibilityv1";
import type { ListAccessLogTopSessionRequest } from "./visibilityv1";
import type { ListAccessLogTopServiceResponse } from "./visibilityv1";
import type { ListAccessLogTopServiceRequest } from "./visibilityv1";
import type { ListAccessLogTopUserResponse } from "./visibilityv1";
import type { ListAccessLogTopUserRequest } from "./visibilityv1";
import type { GetAccessLogDataPointResponse } from "./visibilityv1";
import type { GetAccessLogDataPointRequest } from "./visibilityv1";
import type { ListSSHSessionRecordingResponse } from "./visibilityv1";
import type { ListSSHSessionRecordingRequest } from "./visibilityv1";
import type { SSHSession } from "./visibilityv1";
import type { GetSSHSessionRequest } from "./visibilityv1";
import type { ListSSHSessionResponse } from "./visibilityv1";
import type { ListSSHSessionRequest } from "./visibilityv1";
import type { ListAccessLogResponse } from "./visibilityv1";
import type { ListAccessLogRequest } from "./visibilityv1";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetAccessLogSummaryResponse } from "./visibilityv1";
import type { GetAccessLogSummaryRequest } from "./visibilityv1";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.AccessLogService
 */
export interface IAccessLogServiceClient {
    /**
     * @generated from protobuf rpc: GetAccessLogSummary
     */
    getAccessLogSummary(input: GetAccessLogSummaryRequest, options?: RpcOptions): UnaryCall<GetAccessLogSummaryRequest, GetAccessLogSummaryResponse>;
    /**
     * @generated from protobuf rpc: ListAccessLog
     */
    listAccessLog(input: ListAccessLogRequest, options?: RpcOptions): UnaryCall<ListAccessLogRequest, ListAccessLogResponse>;
    /**
     * @generated from protobuf rpc: ListSSHSession
     */
    listSSHSession(input: ListSSHSessionRequest, options?: RpcOptions): UnaryCall<ListSSHSessionRequest, ListSSHSessionResponse>;
    /**
     * @generated from protobuf rpc: GetSSHSession
     */
    getSSHSession(input: GetSSHSessionRequest, options?: RpcOptions): UnaryCall<GetSSHSessionRequest, SSHSession>;
    /**
     * @generated from protobuf rpc: ListSSHSessionRecording
     */
    listSSHSessionRecording(input: ListSSHSessionRecordingRequest, options?: RpcOptions): UnaryCall<ListSSHSessionRecordingRequest, ListSSHSessionRecordingResponse>;
    /**
     * @generated from protobuf rpc: GetAccessLogDataPoint
     */
    getAccessLogDataPoint(input: GetAccessLogDataPointRequest, options?: RpcOptions): UnaryCall<GetAccessLogDataPointRequest, GetAccessLogDataPointResponse>;
    /**
     * @generated from protobuf rpc: ListAccessLogTopUser
     */
    listAccessLogTopUser(input: ListAccessLogTopUserRequest, options?: RpcOptions): UnaryCall<ListAccessLogTopUserRequest, ListAccessLogTopUserResponse>;
    /**
     * @generated from protobuf rpc: ListAccessLogTopService
     */
    listAccessLogTopService(input: ListAccessLogTopServiceRequest, options?: RpcOptions): UnaryCall<ListAccessLogTopServiceRequest, ListAccessLogTopServiceResponse>;
    /**
     * @generated from protobuf rpc: ListAccessLogTopSession
     */
    listAccessLogTopSession(input: ListAccessLogTopSessionRequest, options?: RpcOptions): UnaryCall<ListAccessLogTopSessionRequest, ListAccessLogTopSessionResponse>;
    /**
     * @generated from protobuf rpc: ListAccessLogTopPolicy
     */
    listAccessLogTopPolicy(input: ListAccessLogTopPolicyRequest, options?: RpcOptions): UnaryCall<ListAccessLogTopPolicyRequest, ListAccessLogTopPolicyResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.AccessLogService
 */
export class AccessLogServiceClient implements IAccessLogServiceClient, ServiceInfo {
    typeName = AccessLogService.typeName;
    methods = AccessLogService.methods;
    options = AccessLogService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetAccessLogSummary
     */
    getAccessLogSummary(input: GetAccessLogSummaryRequest, options?: RpcOptions): UnaryCall<GetAccessLogSummaryRequest, GetAccessLogSummaryResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAccessLogSummaryRequest, GetAccessLogSummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAccessLog
     */
    listAccessLog(input: ListAccessLogRequest, options?: RpcOptions): UnaryCall<ListAccessLogRequest, ListAccessLogResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAccessLogRequest, ListAccessLogResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSSHSession
     */
    listSSHSession(input: ListSSHSessionRequest, options?: RpcOptions): UnaryCall<ListSSHSessionRequest, ListSSHSessionResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSSHSessionRequest, ListSSHSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSSHSession
     */
    getSSHSession(input: GetSSHSessionRequest, options?: RpcOptions): UnaryCall<GetSSHSessionRequest, SSHSession> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSSHSessionRequest, SSHSession>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListSSHSessionRecording
     */
    listSSHSessionRecording(input: ListSSHSessionRecordingRequest, options?: RpcOptions): UnaryCall<ListSSHSessionRecordingRequest, ListSSHSessionRecordingResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListSSHSessionRecordingRequest, ListSSHSessionRecordingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAccessLogDataPoint
     */
    getAccessLogDataPoint(input: GetAccessLogDataPointRequest, options?: RpcOptions): UnaryCall<GetAccessLogDataPointRequest, GetAccessLogDataPointResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAccessLogDataPointRequest, GetAccessLogDataPointResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAccessLogTopUser
     */
    listAccessLogTopUser(input: ListAccessLogTopUserRequest, options?: RpcOptions): UnaryCall<ListAccessLogTopUserRequest, ListAccessLogTopUserResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAccessLogTopUserRequest, ListAccessLogTopUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAccessLogTopService
     */
    listAccessLogTopService(input: ListAccessLogTopServiceRequest, options?: RpcOptions): UnaryCall<ListAccessLogTopServiceRequest, ListAccessLogTopServiceResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAccessLogTopServiceRequest, ListAccessLogTopServiceResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAccessLogTopSession
     */
    listAccessLogTopSession(input: ListAccessLogTopSessionRequest, options?: RpcOptions): UnaryCall<ListAccessLogTopSessionRequest, ListAccessLogTopSessionResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAccessLogTopSessionRequest, ListAccessLogTopSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAccessLogTopPolicy
     */
    listAccessLogTopPolicy(input: ListAccessLogTopPolicyRequest, options?: RpcOptions): UnaryCall<ListAccessLogTopPolicyRequest, ListAccessLogTopPolicyResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAccessLogTopPolicyRequest, ListAccessLogTopPolicyResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.AuthenticationLogService
 */
export interface IAuthenticationLogServiceClient {
    /**
     * @generated from protobuf rpc: ListAuthenticationLog
     */
    listAuthenticationLog(input: ListAuthenticationLogRequest, options?: RpcOptions): UnaryCall<ListAuthenticationLogRequest, ListAuthenticationLogResponse>;
    /**
     * @generated from protobuf rpc: GetAuthenticationLogSummary
     */
    getAuthenticationLogSummary(input: GetAuthenticationLogSummaryRequest, options?: RpcOptions): UnaryCall<GetAuthenticationLogSummaryRequest, GetAuthenticationLogSummaryResponse>;
    /**
     * @generated from protobuf rpc: GetAuthenticationLogDataPoint
     */
    getAuthenticationLogDataPoint(input: GetAuthenticationLogDataPointRequest, options?: RpcOptions): UnaryCall<GetAuthenticationLogDataPointRequest, GetAuthenticationLogDataPointResponse>;
    /**
     * @generated from protobuf rpc: ListAuthenticationLogTopUser
     */
    listAuthenticationLogTopUser(input: ListAuthenticationLogTopUserRequest, options?: RpcOptions): UnaryCall<ListAuthenticationLogTopUserRequest, ListAuthenticationLogTopUserResponse>;
    /**
     * @generated from protobuf rpc: ListAuthenticationLogTopCredential
     */
    listAuthenticationLogTopCredential(input: ListAuthenticationLogTopCredentialRequest, options?: RpcOptions): UnaryCall<ListAuthenticationLogTopCredentialRequest, ListAuthenticationLogTopCredentialResponse>;
    /**
     * @generated from protobuf rpc: ListAuthenticationLogTopIdentityProvider
     */
    listAuthenticationLogTopIdentityProvider(input: ListAuthenticationLogTopIdentityProviderRequest, options?: RpcOptions): UnaryCall<ListAuthenticationLogTopIdentityProviderRequest, ListAuthenticationLogTopIdentityProviderResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.AuthenticationLogService
 */
export class AuthenticationLogServiceClient implements IAuthenticationLogServiceClient, ServiceInfo {
    typeName = AuthenticationLogService.typeName;
    methods = AuthenticationLogService.methods;
    options = AuthenticationLogService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListAuthenticationLog
     */
    listAuthenticationLog(input: ListAuthenticationLogRequest, options?: RpcOptions): UnaryCall<ListAuthenticationLogRequest, ListAuthenticationLogResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuthenticationLogRequest, ListAuthenticationLogResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAuthenticationLogSummary
     */
    getAuthenticationLogSummary(input: GetAuthenticationLogSummaryRequest, options?: RpcOptions): UnaryCall<GetAuthenticationLogSummaryRequest, GetAuthenticationLogSummaryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAuthenticationLogSummaryRequest, GetAuthenticationLogSummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAuthenticationLogDataPoint
     */
    getAuthenticationLogDataPoint(input: GetAuthenticationLogDataPointRequest, options?: RpcOptions): UnaryCall<GetAuthenticationLogDataPointRequest, GetAuthenticationLogDataPointResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAuthenticationLogDataPointRequest, GetAuthenticationLogDataPointResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAuthenticationLogTopUser
     */
    listAuthenticationLogTopUser(input: ListAuthenticationLogTopUserRequest, options?: RpcOptions): UnaryCall<ListAuthenticationLogTopUserRequest, ListAuthenticationLogTopUserResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuthenticationLogTopUserRequest, ListAuthenticationLogTopUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAuthenticationLogTopCredential
     */
    listAuthenticationLogTopCredential(input: ListAuthenticationLogTopCredentialRequest, options?: RpcOptions): UnaryCall<ListAuthenticationLogTopCredentialRequest, ListAuthenticationLogTopCredentialResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuthenticationLogTopCredentialRequest, ListAuthenticationLogTopCredentialResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAuthenticationLogTopIdentityProvider
     */
    listAuthenticationLogTopIdentityProvider(input: ListAuthenticationLogTopIdentityProviderRequest, options?: RpcOptions): UnaryCall<ListAuthenticationLogTopIdentityProviderRequest, ListAuthenticationLogTopIdentityProviderResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuthenticationLogTopIdentityProviderRequest, ListAuthenticationLogTopIdentityProviderResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.AuditLogService
 */
export interface IAuditLogServiceClient {
    /**
     * @generated from protobuf rpc: ListAuditLog
     */
    listAuditLog(input: ListAuditLogRequest, options?: RpcOptions): UnaryCall<ListAuditLogRequest, ListAuditLogResponse>;
    /**
     * @generated from protobuf rpc: GetAuditLogSummary
     */
    getAuditLogSummary(input: GetAuditLogSummaryRequest, options?: RpcOptions): UnaryCall<GetAuditLogSummaryRequest, GetAuditLogSummaryResponse>;
    /**
     * @generated from protobuf rpc: GetAuditLogDataPoint
     */
    getAuditLogDataPoint(input: GetAuditLogDataPointRequest, options?: RpcOptions): UnaryCall<GetAuditLogDataPointRequest, GetAuditLogDataPointResponse>;
    /**
     * @generated from protobuf rpc: ListAuditLogTopUser
     */
    listAuditLogTopUser(input: ListAuditLogTopUserRequest, options?: RpcOptions): UnaryCall<ListAuditLogTopUserRequest, ListAuditLogTopUserResponse>;
    /**
     * @generated from protobuf rpc: ListAuditLogTopSession
     */
    listAuditLogTopSession(input: ListAuditLogTopSessionRequest, options?: RpcOptions): UnaryCall<ListAuditLogTopSessionRequest, ListAuditLogTopSessionResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.AuditLogService
 */
export class AuditLogServiceClient implements IAuditLogServiceClient, ServiceInfo {
    typeName = AuditLogService.typeName;
    methods = AuditLogService.methods;
    options = AuditLogService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListAuditLog
     */
    listAuditLog(input: ListAuditLogRequest, options?: RpcOptions): UnaryCall<ListAuditLogRequest, ListAuditLogResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuditLogRequest, ListAuditLogResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAuditLogSummary
     */
    getAuditLogSummary(input: GetAuditLogSummaryRequest, options?: RpcOptions): UnaryCall<GetAuditLogSummaryRequest, GetAuditLogSummaryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAuditLogSummaryRequest, GetAuditLogSummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAuditLogDataPoint
     */
    getAuditLogDataPoint(input: GetAuditLogDataPointRequest, options?: RpcOptions): UnaryCall<GetAuditLogDataPointRequest, GetAuditLogDataPointResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAuditLogDataPointRequest, GetAuditLogDataPointResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAuditLogTopUser
     */
    listAuditLogTopUser(input: ListAuditLogTopUserRequest, options?: RpcOptions): UnaryCall<ListAuditLogTopUserRequest, ListAuditLogTopUserResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuditLogTopUserRequest, ListAuditLogTopUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ListAuditLogTopSession
     */
    listAuditLogTopSession(input: ListAuditLogTopSessionRequest, options?: RpcOptions): UnaryCall<ListAuditLogTopSessionRequest, ListAuditLogTopSessionResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListAuditLogTopSessionRequest, ListAuditLogTopSessionResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.ComponentLogService
 */
export interface IComponentLogServiceClient {
    /**
     * @generated from protobuf rpc: ListComponentLog
     */
    listComponentLog(input: ListComponentLogRequest, options?: RpcOptions): UnaryCall<ListComponentLogRequest, ListComponentLogResponse>;
    /**
     * @generated from protobuf rpc: GetComponentLogSummary
     */
    getComponentLogSummary(input: GetComponentLogSummaryRequest, options?: RpcOptions): UnaryCall<GetComponentLogSummaryRequest, GetComponentLogSummaryResponse>;
    /**
     * @generated from protobuf rpc: GetComponentLogDataPoint
     */
    getComponentLogDataPoint(input: GetComponentLogDataPointRequest, options?: RpcOptions): UnaryCall<GetComponentLogDataPointRequest, GetComponentLogDataPointResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.ComponentLogService
 */
export class ComponentLogServiceClient implements IComponentLogServiceClient, ServiceInfo {
    typeName = ComponentLogService.typeName;
    methods = ComponentLogService.methods;
    options = ComponentLogService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListComponentLog
     */
    listComponentLog(input: ListComponentLogRequest, options?: RpcOptions): UnaryCall<ListComponentLogRequest, ListComponentLogResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListComponentLogRequest, ListComponentLogResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetComponentLogSummary
     */
    getComponentLogSummary(input: GetComponentLogSummaryRequest, options?: RpcOptions): UnaryCall<GetComponentLogSummaryRequest, GetComponentLogSummaryResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetComponentLogSummaryRequest, GetComponentLogSummaryResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetComponentLogDataPoint
     */
    getComponentLogDataPoint(input: GetComponentLogDataPointRequest, options?: RpcOptions): UnaryCall<GetComponentLogDataPointRequest, GetComponentLogDataPointResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetComponentLogDataPointRequest, GetComponentLogDataPointResponse>("unary", this._transport, method, opt, input);
    }
}
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.MetricsService
 */
export interface IMetricsServiceClient {
    /**
     * @generated from protobuf rpc: GetCounter
     */
    getCounter(input: GetCounterRequest, options?: RpcOptions): UnaryCall<GetCounterRequest, GetCounterResponse>;
    /**
     * @generated from protobuf rpc: GetGauge
     */
    getGauge(input: GetGaugeRequest, options?: RpcOptions): UnaryCall<GetGaugeRequest, GetGaugeResponse>;
    /**
     * @generated from protobuf rpc: GetHistogram
     */
    getHistogram(input: GetHistogramRequest, options?: RpcOptions): UnaryCall<GetHistogramRequest, GetHistogramResponse>;
}
/**
 * @generated from protobuf service octelium.api.main.visibility.v1.MetricsService
 */
export class MetricsServiceClient implements IMetricsServiceClient, ServiceInfo {
    typeName = MetricsService.typeName;
    methods = MetricsService.methods;
    options = MetricsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetCounter
     */
    getCounter(input: GetCounterRequest, options?: RpcOptions): UnaryCall<GetCounterRequest, GetCounterResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetCounterRequest, GetCounterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetGauge
     */
    getGauge(input: GetGaugeRequest, options?: RpcOptions): UnaryCall<GetGaugeRequest, GetGaugeResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetGaugeRequest, GetGaugeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetHistogram
     */
    getHistogram(input: GetHistogramRequest, options?: RpcOptions): UnaryCall<GetHistogramRequest, GetHistogramResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetHistogramRequest, GetHistogramResponse>("unary", this._transport, method, opt, input);
    }
}
