name: tests-unit-test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - dev*
      - t-*
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
      redis:
        image: redis
        ports:
          - 6379:6379
      minio:
        env:
          AWS_ACCESS_KEY_ID: minioadmin
          AWS_SECRET_ACCESS_KEY: minioadmin
        image: fclairamb/minio-github-actions
        ports:
          - 9000:9000
      vault:
        image: hashicorp/vault
        ports:
          - 8200:8200
        env:
          VAULT_DEV_ROOT_TOKEN_ID: root
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    steps:
      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
      - name: Set ENV variables
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: for v in `cat .github/workflows/env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
      - name: Create database
        run: psql -h localhost -U postgres -c 'CREATE DATABASE octelium;'
        env:
          PGPASSWORD: postgres
      - name: Run tests
        run: |
          if [ "$OCTELIUM_PRIVATE_REPO" == "true" ]; then
            git config --global url."https://${{ secrets.OCT_MAIN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
            go env -w GOPRIVATE="github.com/octelium/*"
          fi
          go version
          which go
          gocmd=$(which go)
          sudo -E $gocmd version
          sudo -E $gocmd test github.com/octelium/octelium-ee/...
